package errkit

import (
	"fmt"
)

// AddStack will wrap error with caller function name.
// Argument str will auto generated by pkg/errkit/errkitcli/main.go.
func AddFuncName(str string, err error) error {
	return fmt.Errorf("%s:: %w", str, err)
}
