// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"golang-clean-architecture/internal/gateway/messaging"
	"golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that AddressProducerMock does implement messaging.AddressProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.AddressProducer = &AddressProducerMock{}

// AddressProducerMock is a mock implementation of messaging.AddressProducer.
//
//	func TestSomethingThatUsesAddressProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.AddressProducer
//		mockedAddressProducer := &AddressProducerMock{
//			SendFunc: func(event *model.AddressEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedAddressProducer in code that requires messaging.AddressProducer
//		// and then make assertions.
//
//	}
type AddressProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(event *model.AddressEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Event is the event argument value.
			Event *model.AddressEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *AddressProducerMock) Send(event *model.AddressEvent) error {
	if mock.SendFunc == nil {
		panic("AddressProducerMock.SendFunc: method is nil but AddressProducer.Send was just called")
	}
	callInfo := struct {
		Event *model.AddressEvent
	}{
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedAddressProducer.SendCalls())
func (mock *AddressProducerMock) SendCalls() []struct {
	Event *model.AddressEvent
} {
	var calls []struct {
		Event *model.AddressEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
