// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that CommentRepositoryMock does implement repository.CommentRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.CommentRepository = &CommentRepositoryMock{}

// CommentRepositoryMock is a mock implementation of repository.CommentRepository.
//
//	func TestSomethingThatUsesCommentRepository(t *testing.T) {
//
//		// make and configure a mocked repository.CommentRepository
//		mockedCommentRepository := &CommentRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.Comment) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedCommentRepository in code that requires repository.CommentRepository
//		// and then make assertions.
//
//	}
type CommentRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.Comment) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.Comment
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *CommentRepositoryMock) Create(ctx context.Context, db *gorm.DB, entityMoqParam *entity.Comment) error {
	if mock.CreateFunc == nil {
		panic("CommentRepositoryMock.CreateFunc: method is nil but CommentRepository.Create was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.Comment
	}{
		Ctx:            ctx,
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, entityMoqParam)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedCommentRepository.CreateCalls())
func (mock *CommentRepositoryMock) CreateCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	EntityMoqParam *entity.Comment
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.Comment
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
