// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"golang-clean-architecture/internal/gateway/messaging"
	"golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that ContactProducerMock does implement messaging.ContactProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.ContactProducer = &ContactProducerMock{}

// ContactProducerMock is a mock implementation of messaging.ContactProducer.
//
//	func TestSomethingThatUsesContactProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.ContactProducer
//		mockedContactProducer := &ContactProducerMock{
//			SendFunc: func(event *model.ContactEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedContactProducer in code that requires messaging.ContactProducer
//		// and then make assertions.
//
//	}
type ContactProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(event *model.ContactEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Event is the event argument value.
			Event *model.ContactEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *ContactProducerMock) Send(event *model.ContactEvent) error {
	if mock.SendFunc == nil {
		panic("ContactProducerMock.SendFunc: method is nil but ContactProducer.Send was just called")
	}
	callInfo := struct {
		Event *model.ContactEvent
	}{
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedContactProducer.SendCalls())
func (mock *ContactProducerMock) SendCalls() []struct {
	Event *model.ContactEvent
} {
	var calls []struct {
		Event *model.ContactEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
