// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"golang-clean-architecture/internal/entity"
	"golang-clean-architecture/internal/model"
	"golang-clean-architecture/internal/repository"
	"sync"

	"gorm.io/gorm"
)

// Ensure, that ContactRepositoryMock does implement repository.ContactRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ContactRepository = &ContactRepositoryMock{}

// ContactRepositoryMock is a mock implementation of repository.ContactRepository.
//
//	func TestSomethingThatUsesContactRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ContactRepository
//		mockedContactRepository := &ContactRepositoryMock{
//			CountByIdFunc: func(db *gorm.DB, id any) (int64, error) {
//				panic("mock out the CountById method")
//			},
//			CreateFunc: func(db *gorm.DB, entityMoqParam *entity.Contact) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(db *gorm.DB, entityMoqParam *entity.Contact) error {
//				panic("mock out the Delete method")
//			},
//			FindByIdFunc: func(db *gorm.DB, entityMoqParam *entity.Contact, id any) error {
//				panic("mock out the FindById method")
//			},
//			FindByIdAndUserIdFunc: func(db *gorm.DB, contact *entity.Contact, id string, userId string) error {
//				panic("mock out the FindByIdAndUserId method")
//			},
//			SearchFunc: func(db *gorm.DB, request *model.SearchContactRequest) ([]entity.Contact, int64, error) {
//				panic("mock out the Search method")
//			},
//			UpdateFunc: func(db *gorm.DB, entityMoqParam *entity.Contact) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedContactRepository in code that requires repository.ContactRepository
//		// and then make assertions.
//
//	}
type ContactRepositoryMock struct {
	// CountByIdFunc mocks the CountById method.
	CountByIdFunc func(db *gorm.DB, id any) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(db *gorm.DB, entityMoqParam *entity.Contact) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(db *gorm.DB, entityMoqParam *entity.Contact) error

	// FindByIdFunc mocks the FindById method.
	FindByIdFunc func(db *gorm.DB, entityMoqParam *entity.Contact, id any) error

	// FindByIdAndUserIdFunc mocks the FindByIdAndUserId method.
	FindByIdAndUserIdFunc func(db *gorm.DB, contact *entity.Contact, id string, userId string) error

	// SearchFunc mocks the Search method.
	SearchFunc func(db *gorm.DB, request *model.SearchContactRequest) ([]entity.Contact, int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(db *gorm.DB, entityMoqParam *entity.Contact) error

	// calls tracks calls to the methods.
	calls struct {
		// CountById holds details about calls to the CountById method.
		CountById []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID any
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.Contact
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.Contact
		}
		// FindById holds details about calls to the FindById method.
		FindById []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.Contact
			// ID is the id argument value.
			ID any
		}
		// FindByIdAndUserId holds details about calls to the FindByIdAndUserId method.
		FindByIdAndUserId []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// Contact is the contact argument value.
			Contact *entity.Contact
			// ID is the id argument value.
			ID string
			// UserId is the userId argument value.
			UserId string
		}
		// Search holds details about calls to the Search method.
		Search []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// Request is the request argument value.
			Request *model.SearchContactRequest
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.Contact
		}
	}
	lockCountById         sync.RWMutex
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockFindById          sync.RWMutex
	lockFindByIdAndUserId sync.RWMutex
	lockSearch            sync.RWMutex
	lockUpdate            sync.RWMutex
}

// CountById calls CountByIdFunc.
func (mock *ContactRepositoryMock) CountById(db *gorm.DB, id any) (int64, error) {
	if mock.CountByIdFunc == nil {
		panic("ContactRepositoryMock.CountByIdFunc: method is nil but ContactRepository.CountById was just called")
	}
	callInfo := struct {
		Db *gorm.DB
		ID any
	}{
		Db: db,
		ID: id,
	}
	mock.lockCountById.Lock()
	mock.calls.CountById = append(mock.calls.CountById, callInfo)
	mock.lockCountById.Unlock()
	return mock.CountByIdFunc(db, id)
}

// CountByIdCalls gets all the calls that were made to CountById.
// Check the length with:
//
//	len(mockedContactRepository.CountByIdCalls())
func (mock *ContactRepositoryMock) CountByIdCalls() []struct {
	Db *gorm.DB
	ID any
} {
	var calls []struct {
		Db *gorm.DB
		ID any
	}
	mock.lockCountById.RLock()
	calls = mock.calls.CountById
	mock.lockCountById.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ContactRepositoryMock) Create(db *gorm.DB, entityMoqParam *entity.Contact) error {
	if mock.CreateFunc == nil {
		panic("ContactRepositoryMock.CreateFunc: method is nil but ContactRepository.Create was just called")
	}
	callInfo := struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}{
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(db, entityMoqParam)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedContactRepository.CreateCalls())
func (mock *ContactRepositoryMock) CreateCalls() []struct {
	Db             *gorm.DB
	EntityMoqParam *entity.Contact
} {
	var calls []struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ContactRepositoryMock) Delete(db *gorm.DB, entityMoqParam *entity.Contact) error {
	if mock.DeleteFunc == nil {
		panic("ContactRepositoryMock.DeleteFunc: method is nil but ContactRepository.Delete was just called")
	}
	callInfo := struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}{
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(db, entityMoqParam)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedContactRepository.DeleteCalls())
func (mock *ContactRepositoryMock) DeleteCalls() []struct {
	Db             *gorm.DB
	EntityMoqParam *entity.Contact
} {
	var calls []struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindById calls FindByIdFunc.
func (mock *ContactRepositoryMock) FindById(db *gorm.DB, entityMoqParam *entity.Contact, id any) error {
	if mock.FindByIdFunc == nil {
		panic("ContactRepositoryMock.FindByIdFunc: method is nil but ContactRepository.FindById was just called")
	}
	callInfo := struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
		ID             any
	}{
		Db:             db,
		EntityMoqParam: entityMoqParam,
		ID:             id,
	}
	mock.lockFindById.Lock()
	mock.calls.FindById = append(mock.calls.FindById, callInfo)
	mock.lockFindById.Unlock()
	return mock.FindByIdFunc(db, entityMoqParam, id)
}

// FindByIdCalls gets all the calls that were made to FindById.
// Check the length with:
//
//	len(mockedContactRepository.FindByIdCalls())
func (mock *ContactRepositoryMock) FindByIdCalls() []struct {
	Db             *gorm.DB
	EntityMoqParam *entity.Contact
	ID             any
} {
	var calls []struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
		ID             any
	}
	mock.lockFindById.RLock()
	calls = mock.calls.FindById
	mock.lockFindById.RUnlock()
	return calls
}

// FindByIdAndUserId calls FindByIdAndUserIdFunc.
func (mock *ContactRepositoryMock) FindByIdAndUserId(db *gorm.DB, contact *entity.Contact, id string, userId string) error {
	if mock.FindByIdAndUserIdFunc == nil {
		panic("ContactRepositoryMock.FindByIdAndUserIdFunc: method is nil but ContactRepository.FindByIdAndUserId was just called")
	}
	callInfo := struct {
		Db      *gorm.DB
		Contact *entity.Contact
		ID      string
		UserId  string
	}{
		Db:      db,
		Contact: contact,
		ID:      id,
		UserId:  userId,
	}
	mock.lockFindByIdAndUserId.Lock()
	mock.calls.FindByIdAndUserId = append(mock.calls.FindByIdAndUserId, callInfo)
	mock.lockFindByIdAndUserId.Unlock()
	return mock.FindByIdAndUserIdFunc(db, contact, id, userId)
}

// FindByIdAndUserIdCalls gets all the calls that were made to FindByIdAndUserId.
// Check the length with:
//
//	len(mockedContactRepository.FindByIdAndUserIdCalls())
func (mock *ContactRepositoryMock) FindByIdAndUserIdCalls() []struct {
	Db      *gorm.DB
	Contact *entity.Contact
	ID      string
	UserId  string
} {
	var calls []struct {
		Db      *gorm.DB
		Contact *entity.Contact
		ID      string
		UserId  string
	}
	mock.lockFindByIdAndUserId.RLock()
	calls = mock.calls.FindByIdAndUserId
	mock.lockFindByIdAndUserId.RUnlock()
	return calls
}

// Search calls SearchFunc.
func (mock *ContactRepositoryMock) Search(db *gorm.DB, request *model.SearchContactRequest) ([]entity.Contact, int64, error) {
	if mock.SearchFunc == nil {
		panic("ContactRepositoryMock.SearchFunc: method is nil but ContactRepository.Search was just called")
	}
	callInfo := struct {
		Db      *gorm.DB
		Request *model.SearchContactRequest
	}{
		Db:      db,
		Request: request,
	}
	mock.lockSearch.Lock()
	mock.calls.Search = append(mock.calls.Search, callInfo)
	mock.lockSearch.Unlock()
	return mock.SearchFunc(db, request)
}

// SearchCalls gets all the calls that were made to Search.
// Check the length with:
//
//	len(mockedContactRepository.SearchCalls())
func (mock *ContactRepositoryMock) SearchCalls() []struct {
	Db      *gorm.DB
	Request *model.SearchContactRequest
} {
	var calls []struct {
		Db      *gorm.DB
		Request *model.SearchContactRequest
	}
	mock.lockSearch.RLock()
	calls = mock.calls.Search
	mock.lockSearch.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ContactRepositoryMock) Update(db *gorm.DB, entityMoqParam *entity.Contact) error {
	if mock.UpdateFunc == nil {
		panic("ContactRepositoryMock.UpdateFunc: method is nil but ContactRepository.Update was just called")
	}
	callInfo := struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}{
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(db, entityMoqParam)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedContactRepository.UpdateCalls())
func (mock *ContactRepositoryMock) UpdateCalls() []struct {
	Db             *gorm.DB
	EntityMoqParam *entity.Contact
} {
	var calls []struct {
		Db             *gorm.DB
		EntityMoqParam *entity.Contact
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
