// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that FollowRepositoryMock does implement repository.FollowRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.FollowRepository = &FollowRepositoryMock{}

// FollowRepositoryMock is a mock implementation of repository.FollowRepository.
//
//	func TestSomethingThatUsesFollowRepository(t *testing.T) {
//
//		// make and configure a mocked repository.FollowRepository
//		mockedFollowRepository := &FollowRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, follow *entity.Follow) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedFollowRepository in code that requires repository.FollowRepository
//		// and then make assertions.
//
//	}
type FollowRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, follow *entity.Follow) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Follow is the follow argument value.
			Follow *entity.Follow
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *FollowRepositoryMock) Create(ctx context.Context, db *gorm.DB, follow *entity.Follow) error {
	if mock.CreateFunc == nil {
		panic("FollowRepositoryMock.CreateFunc: method is nil but FollowRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Db     *gorm.DB
		Follow *entity.Follow
	}{
		Ctx:    ctx,
		Db:     db,
		Follow: follow,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, follow)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedFollowRepository.CreateCalls())
func (mock *FollowRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Db     *gorm.DB
	Follow *entity.Follow
} {
	var calls []struct {
		Ctx    context.Context
		Db     *gorm.DB
		Follow *entity.Follow
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
