// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/messaging"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that ImageLikedProducerMock does implement messaging.ImageLikedProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.ImageLikedProducer = &ImageLikedProducerMock{}

// ImageLikedProducerMock is a mock implementation of messaging.ImageLikedProducer.
//
//	func TestSomethingThatUsesImageLikedProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.ImageLikedProducer
//		mockedImageLikedProducer := &ImageLikedProducerMock{
//			SendFunc: func(ctx context.Context, event *model.ImageLikedEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedImageLikedProducer in code that requires messaging.ImageLikedProducer
//		// and then make assertions.
//
//	}
type ImageLikedProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, event *model.ImageLikedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageLikedEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *ImageLikedProducerMock) Send(ctx context.Context, event *model.ImageLikedEvent) error {
	if mock.SendFunc == nil {
		panic("ImageLikedProducerMock.SendFunc: method is nil but ImageLikedProducer.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageLikedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedImageLikedProducer.SendCalls())
func (mock *ImageLikedProducerMock) SendCalls() []struct {
	Ctx   context.Context
	Event *model.ImageLikedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageLikedEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
