// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that ImageRepositoryMock does implement repository.ImageRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ImageRepository = &ImageRepositoryMock{}

// ImageRepositoryMock is a mock implementation of repository.ImageRepository.
//
//	func TestSomethingThatUsesImageRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ImageRepository
//		mockedImageRepository := &ImageRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, image *entity.Image) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedImageRepository in code that requires repository.ImageRepository
//		// and then make assertions.
//
//	}
type ImageRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, image *entity.Image) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Image is the image argument value.
			Image *entity.Image
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ImageRepositoryMock) Create(ctx context.Context, db *gorm.DB, image *entity.Image) error {
	if mock.CreateFunc == nil {
		panic("ImageRepositoryMock.CreateFunc: method is nil but ImageRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
	}{
		Ctx:   ctx,
		Db:    db,
		Image: image,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, image)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedImageRepository.CreateCalls())
func (mock *ImageRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	Image *entity.Image
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
