// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
)

// Ensure, that ImageRepositoryMock does implement repository.ImageRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ImageRepository = &ImageRepositoryMock{}

// ImageRepositoryMock is a mock implementation of repository.ImageRepository.
//
//	func TestSomethingThatUsesImageRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ImageRepository
//		mockedImageRepository := &ImageRepositoryMock{
//		}
//
//		// use mockedImageRepository in code that requires repository.ImageRepository
//		// and then make assertions.
//
//	}
type ImageRepositoryMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
