// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"github.com/Hidayathamir/golang-clean-architecture/internal/usecase/image"
	"sync"
)

// Ensure, that ImageUsecaseMock does implement image.ImageUsecase.
// If this is not the case, regenerate this file with moq.
var _ image.ImageUsecase = &ImageUsecaseMock{}

// ImageUsecaseMock is a mock implementation of image.ImageUsecase.
//
//	func TestSomethingThatUsesImageUsecase(t *testing.T) {
//
//		// make and configure a mocked image.ImageUsecase
//		mockedImageUsecase := &ImageUsecaseMock{
//			CommentFunc: func(ctx context.Context, req *model.CommentImageRequest) error {
//				panic("mock out the Comment method")
//			},
//			GetCommentFunc: func(ctx context.Context, req *model.GetCommentRequest) (model.CommentResponseList, error) {
//				panic("mock out the GetComment method")
//			},
//			GetImageFunc: func(ctx context.Context, req *model.GetImageRequest) (*model.ImageResponse, error) {
//				panic("mock out the GetImage method")
//			},
//			GetLikeFunc: func(ctx context.Context, req *model.GetLikeRequest) (model.LikeResponseList, error) {
//				panic("mock out the GetLike method")
//			},
//			LikeFunc: func(ctx context.Context, req *model.LikeImageRequest) error {
//				panic("mock out the Like method")
//			},
//			UploadFunc: func(ctx context.Context, req *model.UploadImageRequest) (*model.ImageResponse, error) {
//				panic("mock out the Upload method")
//			},
//		}
//
//		// use mockedImageUsecase in code that requires image.ImageUsecase
//		// and then make assertions.
//
//	}
type ImageUsecaseMock struct {
	// CommentFunc mocks the Comment method.
	CommentFunc func(ctx context.Context, req *model.CommentImageRequest) error

	// GetCommentFunc mocks the GetComment method.
	GetCommentFunc func(ctx context.Context, req *model.GetCommentRequest) (model.CommentResponseList, error)

	// GetImageFunc mocks the GetImage method.
	GetImageFunc func(ctx context.Context, req *model.GetImageRequest) (*model.ImageResponse, error)

	// GetLikeFunc mocks the GetLike method.
	GetLikeFunc func(ctx context.Context, req *model.GetLikeRequest) (model.LikeResponseList, error)

	// LikeFunc mocks the Like method.
	LikeFunc func(ctx context.Context, req *model.LikeImageRequest) error

	// UploadFunc mocks the Upload method.
	UploadFunc func(ctx context.Context, req *model.UploadImageRequest) (*model.ImageResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Comment holds details about calls to the Comment method.
		Comment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.CommentImageRequest
		}
		// GetComment holds details about calls to the GetComment method.
		GetComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.GetCommentRequest
		}
		// GetImage holds details about calls to the GetImage method.
		GetImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.GetImageRequest
		}
		// GetLike holds details about calls to the GetLike method.
		GetLike []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.GetLikeRequest
		}
		// Like holds details about calls to the Like method.
		Like []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.LikeImageRequest
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.UploadImageRequest
		}
	}
	lockComment    sync.RWMutex
	lockGetComment sync.RWMutex
	lockGetImage   sync.RWMutex
	lockGetLike    sync.RWMutex
	lockLike       sync.RWMutex
	lockUpload     sync.RWMutex
}

// Comment calls CommentFunc.
func (mock *ImageUsecaseMock) Comment(ctx context.Context, req *model.CommentImageRequest) error {
	if mock.CommentFunc == nil {
		panic("ImageUsecaseMock.CommentFunc: method is nil but ImageUsecase.Comment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.CommentImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockComment.Lock()
	mock.calls.Comment = append(mock.calls.Comment, callInfo)
	mock.lockComment.Unlock()
	return mock.CommentFunc(ctx, req)
}

// CommentCalls gets all the calls that were made to Comment.
// Check the length with:
//
//	len(mockedImageUsecase.CommentCalls())
func (mock *ImageUsecaseMock) CommentCalls() []struct {
	Ctx context.Context
	Req *model.CommentImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.CommentImageRequest
	}
	mock.lockComment.RLock()
	calls = mock.calls.Comment
	mock.lockComment.RUnlock()
	return calls
}

// GetComment calls GetCommentFunc.
func (mock *ImageUsecaseMock) GetComment(ctx context.Context, req *model.GetCommentRequest) (model.CommentResponseList, error) {
	if mock.GetCommentFunc == nil {
		panic("ImageUsecaseMock.GetCommentFunc: method is nil but ImageUsecase.GetComment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.GetCommentRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetComment.Lock()
	mock.calls.GetComment = append(mock.calls.GetComment, callInfo)
	mock.lockGetComment.Unlock()
	return mock.GetCommentFunc(ctx, req)
}

// GetCommentCalls gets all the calls that were made to GetComment.
// Check the length with:
//
//	len(mockedImageUsecase.GetCommentCalls())
func (mock *ImageUsecaseMock) GetCommentCalls() []struct {
	Ctx context.Context
	Req *model.GetCommentRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.GetCommentRequest
	}
	mock.lockGetComment.RLock()
	calls = mock.calls.GetComment
	mock.lockGetComment.RUnlock()
	return calls
}

// GetImage calls GetImageFunc.
func (mock *ImageUsecaseMock) GetImage(ctx context.Context, req *model.GetImageRequest) (*model.ImageResponse, error) {
	if mock.GetImageFunc == nil {
		panic("ImageUsecaseMock.GetImageFunc: method is nil but ImageUsecase.GetImage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.GetImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetImage.Lock()
	mock.calls.GetImage = append(mock.calls.GetImage, callInfo)
	mock.lockGetImage.Unlock()
	return mock.GetImageFunc(ctx, req)
}

// GetImageCalls gets all the calls that were made to GetImage.
// Check the length with:
//
//	len(mockedImageUsecase.GetImageCalls())
func (mock *ImageUsecaseMock) GetImageCalls() []struct {
	Ctx context.Context
	Req *model.GetImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.GetImageRequest
	}
	mock.lockGetImage.RLock()
	calls = mock.calls.GetImage
	mock.lockGetImage.RUnlock()
	return calls
}

// GetLike calls GetLikeFunc.
func (mock *ImageUsecaseMock) GetLike(ctx context.Context, req *model.GetLikeRequest) (model.LikeResponseList, error) {
	if mock.GetLikeFunc == nil {
		panic("ImageUsecaseMock.GetLikeFunc: method is nil but ImageUsecase.GetLike was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.GetLikeRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetLike.Lock()
	mock.calls.GetLike = append(mock.calls.GetLike, callInfo)
	mock.lockGetLike.Unlock()
	return mock.GetLikeFunc(ctx, req)
}

// GetLikeCalls gets all the calls that were made to GetLike.
// Check the length with:
//
//	len(mockedImageUsecase.GetLikeCalls())
func (mock *ImageUsecaseMock) GetLikeCalls() []struct {
	Ctx context.Context
	Req *model.GetLikeRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.GetLikeRequest
	}
	mock.lockGetLike.RLock()
	calls = mock.calls.GetLike
	mock.lockGetLike.RUnlock()
	return calls
}

// Like calls LikeFunc.
func (mock *ImageUsecaseMock) Like(ctx context.Context, req *model.LikeImageRequest) error {
	if mock.LikeFunc == nil {
		panic("ImageUsecaseMock.LikeFunc: method is nil but ImageUsecase.Like was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.LikeImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLike.Lock()
	mock.calls.Like = append(mock.calls.Like, callInfo)
	mock.lockLike.Unlock()
	return mock.LikeFunc(ctx, req)
}

// LikeCalls gets all the calls that were made to Like.
// Check the length with:
//
//	len(mockedImageUsecase.LikeCalls())
func (mock *ImageUsecaseMock) LikeCalls() []struct {
	Ctx context.Context
	Req *model.LikeImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.LikeImageRequest
	}
	mock.lockLike.RLock()
	calls = mock.calls.Like
	mock.lockLike.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *ImageUsecaseMock) Upload(ctx context.Context, req *model.UploadImageRequest) (*model.ImageResponse, error) {
	if mock.UploadFunc == nil {
		panic("ImageUsecaseMock.UploadFunc: method is nil but ImageUsecase.Upload was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.UploadImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(ctx, req)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//
//	len(mockedImageUsecase.UploadCalls())
func (mock *ImageUsecaseMock) UploadCalls() []struct {
	Ctx context.Context
	Req *model.UploadImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.UploadImageRequest
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}
