// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/messaging"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that ImageUploadedProducerMock does implement messaging.ImageUploadedProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.ImageUploadedProducer = &ImageUploadedProducerMock{}

// ImageUploadedProducerMock is a mock implementation of messaging.ImageUploadedProducer.
//
//	func TestSomethingThatUsesImageUploadedProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.ImageUploadedProducer
//		mockedImageUploadedProducer := &ImageUploadedProducerMock{
//			SendFunc: func(ctx context.Context, event *model.ImageUploadedEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedImageUploadedProducer in code that requires messaging.ImageUploadedProducer
//		// and then make assertions.
//
//	}
type ImageUploadedProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, event *model.ImageUploadedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageUploadedEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *ImageUploadedProducerMock) Send(ctx context.Context, event *model.ImageUploadedEvent) error {
	if mock.SendFunc == nil {
		panic("ImageUploadedProducerMock.SendFunc: method is nil but ImageUploadedProducer.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageUploadedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedImageUploadedProducer.SendCalls())
func (mock *ImageUploadedProducerMock) SendCalls() []struct {
	Ctx   context.Context
	Event *model.ImageUploadedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageUploadedEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
