// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"github.com/Hidayathamir/golang-clean-architecture/internal/usecase/image"
	"sync"
)

// Ensure, that ImageUsecaseMock does implement image.ImageUsecase.
// If this is not the case, regenerate this file with moq.
var _ image.ImageUsecase = &ImageUsecaseMock{}

// ImageUsecaseMock is a mock implementation of image.ImageUsecase.
//
//	func TestSomethingThatUsesImageUsecase(t *testing.T) {
//
//		// make and configure a mocked image.ImageUsecase
//		mockedImageUsecase := &ImageUsecaseMock{
//			CommentFunc: func(ctx context.Context, req *model.CommentImageRequest) error {
//				panic("mock out the Comment method")
//			},
//			LikeFunc: func(ctx context.Context, req *model.LikeImageRequest) error {
//				panic("mock out the Like method")
//			},
//			UploadFunc: func(ctx context.Context, req *model.UploadImageRequest) error {
//				panic("mock out the Upload method")
//			},
//		}
//
//		// use mockedImageUsecase in code that requires image.ImageUsecase
//		// and then make assertions.
//
//	}
type ImageUsecaseMock struct {
	// CommentFunc mocks the Comment method.
	CommentFunc func(ctx context.Context, req *model.CommentImageRequest) error

	// LikeFunc mocks the Like method.
	LikeFunc func(ctx context.Context, req *model.LikeImageRequest) error

	// UploadFunc mocks the Upload method.
	UploadFunc func(ctx context.Context, req *model.UploadImageRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// Comment holds details about calls to the Comment method.
		Comment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.CommentImageRequest
		}
		// Like holds details about calls to the Like method.
		Like []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.LikeImageRequest
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.UploadImageRequest
		}
	}
	lockComment sync.RWMutex
	lockLike    sync.RWMutex
	lockUpload  sync.RWMutex
}

// Comment calls CommentFunc.
func (mock *ImageUsecaseMock) Comment(ctx context.Context, req *model.CommentImageRequest) error {
	if mock.CommentFunc == nil {
		panic("ImageUsecaseMock.CommentFunc: method is nil but ImageUsecase.Comment was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.CommentImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockComment.Lock()
	mock.calls.Comment = append(mock.calls.Comment, callInfo)
	mock.lockComment.Unlock()
	return mock.CommentFunc(ctx, req)
}

// CommentCalls gets all the calls that were made to Comment.
// Check the length with:
//
//	len(mockedImageUsecase.CommentCalls())
func (mock *ImageUsecaseMock) CommentCalls() []struct {
	Ctx context.Context
	Req *model.CommentImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.CommentImageRequest
	}
	mock.lockComment.RLock()
	calls = mock.calls.Comment
	mock.lockComment.RUnlock()
	return calls
}

// Like calls LikeFunc.
func (mock *ImageUsecaseMock) Like(ctx context.Context, req *model.LikeImageRequest) error {
	if mock.LikeFunc == nil {
		panic("ImageUsecaseMock.LikeFunc: method is nil but ImageUsecase.Like was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.LikeImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLike.Lock()
	mock.calls.Like = append(mock.calls.Like, callInfo)
	mock.lockLike.Unlock()
	return mock.LikeFunc(ctx, req)
}

// LikeCalls gets all the calls that were made to Like.
// Check the length with:
//
//	len(mockedImageUsecase.LikeCalls())
func (mock *ImageUsecaseMock) LikeCalls() []struct {
	Ctx context.Context
	Req *model.LikeImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.LikeImageRequest
	}
	mock.lockLike.RLock()
	calls = mock.calls.Like
	mock.lockLike.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *ImageUsecaseMock) Upload(ctx context.Context, req *model.UploadImageRequest) error {
	if mock.UploadFunc == nil {
		panic("ImageUsecaseMock.UploadFunc: method is nil but ImageUsecase.Upload was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.UploadImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(ctx, req)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//
//	len(mockedImageUsecase.UploadCalls())
func (mock *ImageUsecaseMock) UploadCalls() []struct {
	Ctx context.Context
	Req *model.UploadImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *model.UploadImageRequest
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}
