// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/messaging"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that ImageCommentedProducerMock does implement messaging.ImageCommentedProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.ImageCommentedProducer = &ImageCommentedProducerMock{}

// ImageCommentedProducerMock is a mock implementation of messaging.ImageCommentedProducer.
//
//	func TestSomethingThatUsesImageCommentedProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.ImageCommentedProducer
//		mockedImageCommentedProducer := &ImageCommentedProducerMock{
//			SendFunc: func(ctx context.Context, event *model.ImageCommentedEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedImageCommentedProducer in code that requires messaging.ImageCommentedProducer
//		// and then make assertions.
//
//	}
type ImageCommentedProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, event *model.ImageCommentedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageCommentedEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *ImageCommentedProducerMock) Send(ctx context.Context, event *model.ImageCommentedEvent) error {
	if mock.SendFunc == nil {
		panic("ImageCommentedProducerMock.SendFunc: method is nil but ImageCommentedProducer.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageCommentedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedImageCommentedProducer.SendCalls())
func (mock *ImageCommentedProducerMock) SendCalls() []struct {
	Ctx   context.Context
	Event *model.ImageCommentedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageCommentedEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
