// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that LikeRepositoryMock does implement repository.LikeRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.LikeRepository = &LikeRepositoryMock{}

// LikeRepositoryMock is a mock implementation of repository.LikeRepository.
//
//	func TestSomethingThatUsesLikeRepository(t *testing.T) {
//
//		// make and configure a mocked repository.LikeRepository
//		mockedLikeRepository := &LikeRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, like *entity.Like) error {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedLikeRepository in code that requires repository.LikeRepository
//		// and then make assertions.
//
//	}
type LikeRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, like *entity.Like) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Like is the like argument value.
			Like *entity.Like
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *LikeRepositoryMock) Create(ctx context.Context, db *gorm.DB, like *entity.Like) error {
	if mock.CreateFunc == nil {
		panic("LikeRepositoryMock.CreateFunc: method is nil but LikeRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Db   *gorm.DB
		Like *entity.Like
	}{
		Ctx:  ctx,
		Db:   db,
		Like: like,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, like)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedLikeRepository.CreateCalls())
func (mock *LikeRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	Db   *gorm.DB
	Like *entity.Like
} {
	var calls []struct {
		Ctx  context.Context
		Db   *gorm.DB
		Like *entity.Like
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
