// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/dto"
	"github.com/Hidayathamir/golang-clean-architecture/internal/usecase/notif"
	"sync"
)

// Ensure, that NotifUsecaseMock does implement notif.NotifUsecase.
// If this is not the case, regenerate this file with moq.
var _ notif.NotifUsecase = &NotifUsecaseMock{}

// NotifUsecaseMock is a mock implementation of notif.NotifUsecase.
//
//	func TestSomethingThatUsesNotifUsecase(t *testing.T) {
//
//		// make and configure a mocked notif.NotifUsecase
//		mockedNotifUsecase := &NotifUsecaseMock{
//			NotifyFunc: func(ctx context.Context, req dto.NotifyRequest) error {
//				panic("mock out the Notify method")
//			},
//		}
//
//		// use mockedNotifUsecase in code that requires notif.NotifUsecase
//		// and then make assertions.
//
//	}
type NotifUsecaseMock struct {
	// NotifyFunc mocks the Notify method.
	NotifyFunc func(ctx context.Context, req dto.NotifyRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// Notify holds details about calls to the Notify method.
		Notify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req dto.NotifyRequest
		}
	}
	lockNotify sync.RWMutex
}

// Notify calls NotifyFunc.
func (mock *NotifUsecaseMock) Notify(ctx context.Context, req dto.NotifyRequest) error {
	if mock.NotifyFunc == nil {
		panic("NotifUsecaseMock.NotifyFunc: method is nil but NotifUsecase.Notify was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req dto.NotifyRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockNotify.Lock()
	mock.calls.Notify = append(mock.calls.Notify, callInfo)
	mock.lockNotify.Unlock()
	return mock.NotifyFunc(ctx, req)
}

// NotifyCalls gets all the calls that were made to Notify.
// Check the length with:
//
//	len(mockedNotifUsecase.NotifyCalls())
func (mock *NotifUsecaseMock) NotifyCalls() []struct {
	Ctx context.Context
	Req dto.NotifyRequest
} {
	var calls []struct {
		Ctx context.Context
		Req dto.NotifyRequest
	}
	mock.lockNotify.RLock()
	calls = mock.calls.Notify
	mock.lockNotify.RUnlock()
	return calls
}
