// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/dto"
	"github.com/Hidayathamir/golang-clean-architecture/internal/infra/search"
	"sync"
)

// Ensure, that ImageSearchMock does implement search.ImageSearch.
// If this is not the case, regenerate this file with moq.
var _ search.ImageSearch = &ImageSearchMock{}

// ImageSearchMock is a mock implementation of search.ImageSearch.
//
//	func TestSomethingThatUsesImageSearch(t *testing.T) {
//
//		// make and configure a mocked search.ImageSearch
//		mockedImageSearch := &ImageSearchMock{
//			IndexImageFunc: func(ctx context.Context, document *dto.ImageDocument) error {
//				panic("mock out the IndexImage method")
//			},
//		}
//
//		// use mockedImageSearch in code that requires search.ImageSearch
//		// and then make assertions.
//
//	}
type ImageSearchMock struct {
	// IndexImageFunc mocks the IndexImage method.
	IndexImageFunc func(ctx context.Context, document *dto.ImageDocument) error

	// calls tracks calls to the methods.
	calls struct {
		// IndexImage holds details about calls to the IndexImage method.
		IndexImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Document is the document argument value.
			Document *dto.ImageDocument
		}
	}
	lockIndexImage sync.RWMutex
}

// IndexImage calls IndexImageFunc.
func (mock *ImageSearchMock) IndexImage(ctx context.Context, document *dto.ImageDocument) error {
	if mock.IndexImageFunc == nil {
		panic("ImageSearchMock.IndexImageFunc: method is nil but ImageSearch.IndexImage was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Document *dto.ImageDocument
	}{
		Ctx:      ctx,
		Document: document,
	}
	mock.lockIndexImage.Lock()
	mock.calls.IndexImage = append(mock.calls.IndexImage, callInfo)
	mock.lockIndexImage.Unlock()
	return mock.IndexImageFunc(ctx, document)
}

// IndexImageCalls gets all the calls that were made to IndexImage.
// Check the length with:
//
//	len(mockedImageSearch.IndexImageCalls())
func (mock *ImageSearchMock) IndexImageCalls() []struct {
	Ctx      context.Context
	Document *dto.ImageDocument
} {
	var calls []struct {
		Ctx      context.Context
		Document *dto.ImageDocument
	}
	mock.lockIndexImage.RLock()
	calls = mock.calls.IndexImage
	mock.lockIndexImage.RUnlock()
	return calls
}
