// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/infra/cache"
	"sync"
)

// Ensure, that UserCacheMock does implement cache.UserCache.
// If this is not the case, regenerate this file with moq.
var _ cache.UserCache = &UserCacheMock{}

// UserCacheMock is a mock implementation of cache.UserCache.
//
//	func TestSomethingThatUsesUserCache(t *testing.T) {
//
//		// make and configure a mocked cache.UserCache
//		mockedUserCache := &UserCacheMock{
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*entity.User, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(ctx context.Context, user *entity.User) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedUserCache in code that requires cache.UserCache
//		// and then make assertions.
//
//	}
type UserCacheMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*entity.User, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, user *entity.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *entity.User
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *UserCacheMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("UserCacheMock.DeleteFunc: method is nil but UserCache.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserCache.DeleteCalls())
func (mock *UserCacheMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserCacheMock) Get(ctx context.Context, id int64) (*entity.User, error) {
	if mock.GetFunc == nil {
		panic("UserCacheMock.GetFunc: method is nil but UserCache.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserCache.GetCalls())
func (mock *UserCacheMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *UserCacheMock) Set(ctx context.Context, user *entity.User) error {
	if mock.SetFunc == nil {
		panic("UserCacheMock.SetFunc: method is nil but UserCache.Set was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *entity.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, user)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedUserCache.SetCalls())
func (mock *UserCacheMock) SetCalls() []struct {
	Ctx  context.Context
	User *entity.User
} {
	var calls []struct {
		Ctx  context.Context
		User *entity.User
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
