// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that UserRepositoryMock does implement repository.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of repository.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked repository.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountByUsernameFunc: func(ctx context.Context, db *gorm.DB, username string) (int64, error) {
//				panic("mock out the CountByUsername method")
//			},
//			CreateFunc: func(ctx context.Context, db *gorm.DB, user *entity.User) error {
//				panic("mock out the Create method")
//			},
//			FindByIDFunc: func(ctx context.Context, db *gorm.DB, user *entity.User, id int64) error {
//				panic("mock out the FindByID method")
//			},
//			FindByUsernameFunc: func(ctx context.Context, db *gorm.DB, user *entity.User, username string) error {
//				panic("mock out the FindByUsername method")
//			},
//			IncrementFollowerCountAndFollowingCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error {
//				panic("mock out the IncrementFollowerCountAndFollowingCountByID method")
//			},
//			IncrementFollowerCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementFollowerCountByID method")
//			},
//			IncrementFollowingCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementFollowingCountByID method")
//			},
//			UpdateFunc: func(ctx context.Context, db *gorm.DB, user *entity.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires repository.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountByUsernameFunc mocks the CountByUsername method.
	CountByUsernameFunc func(ctx context.Context, db *gorm.DB, username string) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, user *entity.User) error

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, db *gorm.DB, user *entity.User, id int64) error

	// FindByUsernameFunc mocks the FindByUsername method.
	FindByUsernameFunc func(ctx context.Context, db *gorm.DB, user *entity.User, username string) error

	// IncrementFollowerCountAndFollowingCountByIDFunc mocks the IncrementFollowerCountAndFollowingCountByID method.
	IncrementFollowerCountAndFollowingCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error

	// IncrementFollowerCountByIDFunc mocks the IncrementFollowerCountByID method.
	IncrementFollowerCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// IncrementFollowingCountByIDFunc mocks the IncrementFollowingCountByID method.
	IncrementFollowingCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, db *gorm.DB, user *entity.User) error

	// calls tracks calls to the methods.
	calls struct {
		// CountByUsername holds details about calls to the CountByUsername method.
		CountByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Username is the username argument value.
			Username string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// User is the user argument value.
			User *entity.User
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// User is the user argument value.
			User *entity.User
			// ID is the id argument value.
			ID int64
		}
		// FindByUsername holds details about calls to the FindByUsername method.
		FindByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// User is the user argument value.
			User *entity.User
			// Username is the username argument value.
			Username string
		}
		// IncrementFollowerCountAndFollowingCountByID holds details about calls to the IncrementFollowerCountAndFollowingCountByID method.
		IncrementFollowerCountAndFollowingCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// FollowerCount is the followerCount argument value.
			FollowerCount int
			// FollowingCount is the followingCount argument value.
			FollowingCount int
		}
		// IncrementFollowerCountByID holds details about calls to the IncrementFollowerCountByID method.
		IncrementFollowerCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
		// IncrementFollowingCountByID holds details about calls to the IncrementFollowingCountByID method.
		IncrementFollowingCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// User is the user argument value.
			User *entity.User
		}
	}
	lockCountByUsername                             sync.RWMutex
	lockCreate                                      sync.RWMutex
	lockFindByID                                    sync.RWMutex
	lockFindByUsername                              sync.RWMutex
	lockIncrementFollowerCountAndFollowingCountByID sync.RWMutex
	lockIncrementFollowerCountByID                  sync.RWMutex
	lockIncrementFollowingCountByID                 sync.RWMutex
	lockUpdate                                      sync.RWMutex
}

// CountByUsername calls CountByUsernameFunc.
func (mock *UserRepositoryMock) CountByUsername(ctx context.Context, db *gorm.DB, username string) (int64, error) {
	if mock.CountByUsernameFunc == nil {
		panic("UserRepositoryMock.CountByUsernameFunc: method is nil but UserRepository.CountByUsername was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Db       *gorm.DB
		Username string
	}{
		Ctx:      ctx,
		Db:       db,
		Username: username,
	}
	mock.lockCountByUsername.Lock()
	mock.calls.CountByUsername = append(mock.calls.CountByUsername, callInfo)
	mock.lockCountByUsername.Unlock()
	return mock.CountByUsernameFunc(ctx, db, username)
}

// CountByUsernameCalls gets all the calls that were made to CountByUsername.
// Check the length with:
//
//	len(mockedUserRepository.CountByUsernameCalls())
func (mock *UserRepositoryMock) CountByUsernameCalls() []struct {
	Ctx      context.Context
	Db       *gorm.DB
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Db       *gorm.DB
		Username string
	}
	mock.lockCountByUsername.RLock()
	calls = mock.calls.CountByUsername
	mock.lockCountByUsername.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, db *gorm.DB, user *entity.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
	}{
		Ctx:  ctx,
		Db:   db,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	Db   *gorm.DB
	User *entity.User
} {
	var calls []struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(ctx context.Context, db *gorm.DB, user *entity.User, id int64) error {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
		ID   int64
	}{
		Ctx:  ctx,
		Db:   db,
		User: user,
		ID:   id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, db, user, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	Ctx  context.Context
	Db   *gorm.DB
	User *entity.User
	ID   int64
} {
	var calls []struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
		ID   int64
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByUsername calls FindByUsernameFunc.
func (mock *UserRepositoryMock) FindByUsername(ctx context.Context, db *gorm.DB, user *entity.User, username string) error {
	if mock.FindByUsernameFunc == nil {
		panic("UserRepositoryMock.FindByUsernameFunc: method is nil but UserRepository.FindByUsername was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Db       *gorm.DB
		User     *entity.User
		Username string
	}{
		Ctx:      ctx,
		Db:       db,
		User:     user,
		Username: username,
	}
	mock.lockFindByUsername.Lock()
	mock.calls.FindByUsername = append(mock.calls.FindByUsername, callInfo)
	mock.lockFindByUsername.Unlock()
	return mock.FindByUsernameFunc(ctx, db, user, username)
}

// FindByUsernameCalls gets all the calls that were made to FindByUsername.
// Check the length with:
//
//	len(mockedUserRepository.FindByUsernameCalls())
func (mock *UserRepositoryMock) FindByUsernameCalls() []struct {
	Ctx      context.Context
	Db       *gorm.DB
	User     *entity.User
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Db       *gorm.DB
		User     *entity.User
		Username string
	}
	mock.lockFindByUsername.RLock()
	calls = mock.calls.FindByUsername
	mock.lockFindByUsername.RUnlock()
	return calls
}

// IncrementFollowerCountAndFollowingCountByID calls IncrementFollowerCountAndFollowingCountByIDFunc.
func (mock *UserRepositoryMock) IncrementFollowerCountAndFollowingCountByID(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error {
	if mock.IncrementFollowerCountAndFollowingCountByIDFunc == nil {
		panic("UserRepositoryMock.IncrementFollowerCountAndFollowingCountByIDFunc: method is nil but UserRepository.IncrementFollowerCountAndFollowingCountByID was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		ID             int64
		FollowerCount  int
		FollowingCount int
	}{
		Ctx:            ctx,
		Db:             db,
		ID:             id,
		FollowerCount:  followerCount,
		FollowingCount: followingCount,
	}
	mock.lockIncrementFollowerCountAndFollowingCountByID.Lock()
	mock.calls.IncrementFollowerCountAndFollowingCountByID = append(mock.calls.IncrementFollowerCountAndFollowingCountByID, callInfo)
	mock.lockIncrementFollowerCountAndFollowingCountByID.Unlock()
	return mock.IncrementFollowerCountAndFollowingCountByIDFunc(ctx, db, id, followerCount, followingCount)
}

// IncrementFollowerCountAndFollowingCountByIDCalls gets all the calls that were made to IncrementFollowerCountAndFollowingCountByID.
// Check the length with:
//
//	len(mockedUserRepository.IncrementFollowerCountAndFollowingCountByIDCalls())
func (mock *UserRepositoryMock) IncrementFollowerCountAndFollowingCountByIDCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	ID             int64
	FollowerCount  int
	FollowingCount int
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		ID             int64
		FollowerCount  int
		FollowingCount int
	}
	mock.lockIncrementFollowerCountAndFollowingCountByID.RLock()
	calls = mock.calls.IncrementFollowerCountAndFollowingCountByID
	mock.lockIncrementFollowerCountAndFollowingCountByID.RUnlock()
	return calls
}

// IncrementFollowerCountByID calls IncrementFollowerCountByIDFunc.
func (mock *UserRepositoryMock) IncrementFollowerCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementFollowerCountByIDFunc == nil {
		panic("UserRepositoryMock.IncrementFollowerCountByIDFunc: method is nil but UserRepository.IncrementFollowerCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementFollowerCountByID.Lock()
	mock.calls.IncrementFollowerCountByID = append(mock.calls.IncrementFollowerCountByID, callInfo)
	mock.lockIncrementFollowerCountByID.Unlock()
	return mock.IncrementFollowerCountByIDFunc(ctx, db, id, count)
}

// IncrementFollowerCountByIDCalls gets all the calls that were made to IncrementFollowerCountByID.
// Check the length with:
//
//	len(mockedUserRepository.IncrementFollowerCountByIDCalls())
func (mock *UserRepositoryMock) IncrementFollowerCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementFollowerCountByID.RLock()
	calls = mock.calls.IncrementFollowerCountByID
	mock.lockIncrementFollowerCountByID.RUnlock()
	return calls
}

// IncrementFollowingCountByID calls IncrementFollowingCountByIDFunc.
func (mock *UserRepositoryMock) IncrementFollowingCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementFollowingCountByIDFunc == nil {
		panic("UserRepositoryMock.IncrementFollowingCountByIDFunc: method is nil but UserRepository.IncrementFollowingCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementFollowingCountByID.Lock()
	mock.calls.IncrementFollowingCountByID = append(mock.calls.IncrementFollowingCountByID, callInfo)
	mock.lockIncrementFollowingCountByID.Unlock()
	return mock.IncrementFollowingCountByIDFunc(ctx, db, id, count)
}

// IncrementFollowingCountByIDCalls gets all the calls that were made to IncrementFollowingCountByID.
// Check the length with:
//
//	len(mockedUserRepository.IncrementFollowingCountByIDCalls())
func (mock *UserRepositoryMock) IncrementFollowingCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementFollowingCountByID.RLock()
	calls = mock.calls.IncrementFollowingCountByID
	mock.lockIncrementFollowingCountByID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(ctx context.Context, db *gorm.DB, user *entity.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
	}{
		Ctx:  ctx,
		Db:   db,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, db, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	Ctx  context.Context
	Db   *gorm.DB
	User *entity.User
} {
	var calls []struct {
		Ctx  context.Context
		Db   *gorm.DB
		User *entity.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
