// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/rest"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that PaymentClientMock does implement rest.PaymentClient.
// If this is not the case, regenerate this file with moq.
var _ rest.PaymentClient = &PaymentClientMock{}

// PaymentClientMock is a mock implementation of rest.PaymentClient.
//
//	func TestSomethingThatUsesPaymentClient(t *testing.T) {
//
//		// make and configure a mocked rest.PaymentClient
//		mockedPaymentClient := &PaymentClientMock{
//			GetStatusFunc: func(ctx context.Context, req model.PaymentGetStatusRequest) (model.PaymentGetStatusResponse, error) {
//				panic("mock out the GetStatus method")
//			},
//			RefundFunc: func(ctx context.Context, req model.PaymentRefundRequest) (model.PaymentRefundResponse, error) {
//				panic("mock out the Refund method")
//			},
//		}
//
//		// use mockedPaymentClient in code that requires rest.PaymentClient
//		// and then make assertions.
//
//	}
type PaymentClientMock struct {
	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func(ctx context.Context, req model.PaymentGetStatusRequest) (model.PaymentGetStatusResponse, error)

	// RefundFunc mocks the Refund method.
	RefundFunc func(ctx context.Context, req model.PaymentRefundRequest) (model.PaymentRefundResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req model.PaymentGetStatusRequest
		}
		// Refund holds details about calls to the Refund method.
		Refund []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req model.PaymentRefundRequest
		}
	}
	lockGetStatus sync.RWMutex
	lockRefund    sync.RWMutex
}

// GetStatus calls GetStatusFunc.
func (mock *PaymentClientMock) GetStatus(ctx context.Context, req model.PaymentGetStatusRequest) (model.PaymentGetStatusResponse, error) {
	if mock.GetStatusFunc == nil {
		panic("PaymentClientMock.GetStatusFunc: method is nil but PaymentClient.GetStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req model.PaymentGetStatusRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc(ctx, req)
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedPaymentClient.GetStatusCalls())
func (mock *PaymentClientMock) GetStatusCalls() []struct {
	Ctx context.Context
	Req model.PaymentGetStatusRequest
} {
	var calls []struct {
		Ctx context.Context
		Req model.PaymentGetStatusRequest
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}

// Refund calls RefundFunc.
func (mock *PaymentClientMock) Refund(ctx context.Context, req model.PaymentRefundRequest) (model.PaymentRefundResponse, error) {
	if mock.RefundFunc == nil {
		panic("PaymentClientMock.RefundFunc: method is nil but PaymentClient.Refund was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req model.PaymentRefundRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRefund.Lock()
	mock.calls.Refund = append(mock.calls.Refund, callInfo)
	mock.lockRefund.Unlock()
	return mock.RefundFunc(ctx, req)
}

// RefundCalls gets all the calls that were made to Refund.
// Check the length with:
//
//	len(mockedPaymentClient.RefundCalls())
func (mock *PaymentClientMock) RefundCalls() []struct {
	Ctx context.Context
	Req model.PaymentRefundRequest
} {
	var calls []struct {
		Ctx context.Context
		Req model.PaymentRefundRequest
	}
	mock.lockRefund.RLock()
	calls = mock.calls.Refund
	mock.lockRefund.RUnlock()
	return calls
}
