// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/rest"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that S3ClientMock does implement rest.S3Client.
// If this is not the case, regenerate this file with moq.
var _ rest.S3Client = &S3ClientMock{}

// S3ClientMock is a mock implementation of rest.S3Client.
//
//	func TestSomethingThatUsesS3Client(t *testing.T) {
//
//		// make and configure a mocked rest.S3Client
//		mockedS3Client := &S3ClientMock{
//			DeleteObjectFunc: func(ctx context.Context, req model.S3DeleteObjectRequest) (model.S3DeleteObjectResponse, error) {
//				panic("mock out the DeleteObject method")
//			},
//			DownloadFunc: func(ctx context.Context, req model.S3DownloadRequest) (model.S3DownloadResponse, error) {
//				panic("mock out the Download method")
//			},
//			UploadImageFunc: func(ctx context.Context, req model.S3UploadImageRequest) (string, error) {
//				panic("mock out the UploadImage method")
//			},
//		}
//
//		// use mockedS3Client in code that requires rest.S3Client
//		// and then make assertions.
//
//	}
type S3ClientMock struct {
	// DeleteObjectFunc mocks the DeleteObject method.
	DeleteObjectFunc func(ctx context.Context, req model.S3DeleteObjectRequest) (model.S3DeleteObjectResponse, error)

	// DownloadFunc mocks the Download method.
	DownloadFunc func(ctx context.Context, req model.S3DownloadRequest) (model.S3DownloadResponse, error)

	// UploadImageFunc mocks the UploadImage method.
	UploadImageFunc func(ctx context.Context, req model.S3UploadImageRequest) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteObject holds details about calls to the DeleteObject method.
		DeleteObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req model.S3DeleteObjectRequest
		}
		// Download holds details about calls to the Download method.
		Download []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req model.S3DownloadRequest
		}
		// UploadImage holds details about calls to the UploadImage method.
		UploadImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req model.S3UploadImageRequest
		}
	}
	lockDeleteObject sync.RWMutex
	lockDownload     sync.RWMutex
	lockUploadImage  sync.RWMutex
}

// DeleteObject calls DeleteObjectFunc.
func (mock *S3ClientMock) DeleteObject(ctx context.Context, req model.S3DeleteObjectRequest) (model.S3DeleteObjectResponse, error) {
	if mock.DeleteObjectFunc == nil {
		panic("S3ClientMock.DeleteObjectFunc: method is nil but S3Client.DeleteObject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req model.S3DeleteObjectRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockDeleteObject.Lock()
	mock.calls.DeleteObject = append(mock.calls.DeleteObject, callInfo)
	mock.lockDeleteObject.Unlock()
	return mock.DeleteObjectFunc(ctx, req)
}

// DeleteObjectCalls gets all the calls that were made to DeleteObject.
// Check the length with:
//
//	len(mockedS3Client.DeleteObjectCalls())
func (mock *S3ClientMock) DeleteObjectCalls() []struct {
	Ctx context.Context
	Req model.S3DeleteObjectRequest
} {
	var calls []struct {
		Ctx context.Context
		Req model.S3DeleteObjectRequest
	}
	mock.lockDeleteObject.RLock()
	calls = mock.calls.DeleteObject
	mock.lockDeleteObject.RUnlock()
	return calls
}

// Download calls DownloadFunc.
func (mock *S3ClientMock) Download(ctx context.Context, req model.S3DownloadRequest) (model.S3DownloadResponse, error) {
	if mock.DownloadFunc == nil {
		panic("S3ClientMock.DownloadFunc: method is nil but S3Client.Download was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req model.S3DownloadRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockDownload.Lock()
	mock.calls.Download = append(mock.calls.Download, callInfo)
	mock.lockDownload.Unlock()
	return mock.DownloadFunc(ctx, req)
}

// DownloadCalls gets all the calls that were made to Download.
// Check the length with:
//
//	len(mockedS3Client.DownloadCalls())
func (mock *S3ClientMock) DownloadCalls() []struct {
	Ctx context.Context
	Req model.S3DownloadRequest
} {
	var calls []struct {
		Ctx context.Context
		Req model.S3DownloadRequest
	}
	mock.lockDownload.RLock()
	calls = mock.calls.Download
	mock.lockDownload.RUnlock()
	return calls
}

// UploadImage calls UploadImageFunc.
func (mock *S3ClientMock) UploadImage(ctx context.Context, req model.S3UploadImageRequest) (string, error) {
	if mock.UploadImageFunc == nil {
		panic("S3ClientMock.UploadImageFunc: method is nil but S3Client.UploadImage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req model.S3UploadImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockUploadImage.Lock()
	mock.calls.UploadImage = append(mock.calls.UploadImage, callInfo)
	mock.lockUploadImage.Unlock()
	return mock.UploadImageFunc(ctx, req)
}

// UploadImageCalls gets all the calls that were made to UploadImage.
// Check the length with:
//
//	len(mockedS3Client.UploadImageCalls())
func (mock *S3ClientMock) UploadImageCalls() []struct {
	Ctx context.Context
	Req model.S3UploadImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req model.S3UploadImageRequest
	}
	mock.lockUploadImage.RLock()
	calls = mock.calls.UploadImage
	mock.lockUploadImage.RUnlock()
	return calls
}
