// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/dto"
	"github.com/Hidayathamir/golang-clean-architecture/internal/infra/messaging"
	"sync"
)

// Ensure, that NotifProducerMock does implement messaging.NotifProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.NotifProducer = &NotifProducerMock{}

// NotifProducerMock is a mock implementation of messaging.NotifProducer.
//
//	func TestSomethingThatUsesNotifProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.NotifProducer
//		mockedNotifProducer := &NotifProducerMock{
//			SendNotifFunc: func(ctx context.Context, event *dto.NotifEvent) error {
//				panic("mock out the SendNotif method")
//			},
//		}
//
//		// use mockedNotifProducer in code that requires messaging.NotifProducer
//		// and then make assertions.
//
//	}
type NotifProducerMock struct {
	// SendNotifFunc mocks the SendNotif method.
	SendNotifFunc func(ctx context.Context, event *dto.NotifEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// SendNotif holds details about calls to the SendNotif method.
		SendNotif []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *dto.NotifEvent
		}
	}
	lockSendNotif sync.RWMutex
}

// SendNotif calls SendNotifFunc.
func (mock *NotifProducerMock) SendNotif(ctx context.Context, event *dto.NotifEvent) error {
	if mock.SendNotifFunc == nil {
		panic("NotifProducerMock.SendNotifFunc: method is nil but NotifProducer.SendNotif was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *dto.NotifEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSendNotif.Lock()
	mock.calls.SendNotif = append(mock.calls.SendNotif, callInfo)
	mock.lockSendNotif.Unlock()
	return mock.SendNotifFunc(ctx, event)
}

// SendNotifCalls gets all the calls that were made to SendNotif.
// Check the length with:
//
//	len(mockedNotifProducer.SendNotifCalls())
func (mock *NotifProducerMock) SendNotifCalls() []struct {
	Ctx   context.Context
	Event *dto.NotifEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *dto.NotifEvent
	}
	mock.lockSendNotif.RLock()
	calls = mock.calls.SendNotif
	mock.lockSendNotif.RUnlock()
	return calls
}
