// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/usecase/idempotencyusecase"
	"sync"
	"time"
)

// Ensure, that IdempotencyUsecaseMock does implement idempotencyusecase.IdempotencyUsecase.
// If this is not the case, regenerate this file with moq.
var _ idempotencyusecase.IdempotencyUsecase = &IdempotencyUsecaseMock{}

// IdempotencyUsecaseMock is a mock implementation of idempotencyusecase.IdempotencyUsecase.
//
//	func TestSomethingThatUsesIdempotencyUsecase(t *testing.T) {
//
//		// make and configure a mocked idempotencyusecase.IdempotencyUsecase
//		mockedIdempotencyUsecase := &IdempotencyUsecaseMock{
//			DeleteOlderThanFunc: func(ctx context.Context, age time.Duration) (int64, error) {
//				panic("mock out the DeleteOlderThan method")
//			},
//			InsertIfNotExistsFunc: func(ctx context.Context, key string, topic string, partition int32, offset int64) (bool, error) {
//				panic("mock out the InsertIfNotExists method")
//			},
//		}
//
//		// use mockedIdempotencyUsecase in code that requires idempotencyusecase.IdempotencyUsecase
//		// and then make assertions.
//
//	}
type IdempotencyUsecaseMock struct {
	// DeleteOlderThanFunc mocks the DeleteOlderThan method.
	DeleteOlderThanFunc func(ctx context.Context, age time.Duration) (int64, error)

	// InsertIfNotExistsFunc mocks the InsertIfNotExists method.
	InsertIfNotExistsFunc func(ctx context.Context, key string, topic string, partition int32, offset int64) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteOlderThan holds details about calls to the DeleteOlderThan method.
		DeleteOlderThan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Age is the age argument value.
			Age time.Duration
		}
		// InsertIfNotExists holds details about calls to the InsertIfNotExists method.
		InsertIfNotExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Topic is the topic argument value.
			Topic string
			// Partition is the partition argument value.
			Partition int32
			// Offset is the offset argument value.
			Offset int64
		}
	}
	lockDeleteOlderThan   sync.RWMutex
	lockInsertIfNotExists sync.RWMutex
}

// DeleteOlderThan calls DeleteOlderThanFunc.
func (mock *IdempotencyUsecaseMock) DeleteOlderThan(ctx context.Context, age time.Duration) (int64, error) {
	if mock.DeleteOlderThanFunc == nil {
		panic("IdempotencyUsecaseMock.DeleteOlderThanFunc: method is nil but IdempotencyUsecase.DeleteOlderThan was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Age time.Duration
	}{
		Ctx: ctx,
		Age: age,
	}
	mock.lockDeleteOlderThan.Lock()
	mock.calls.DeleteOlderThan = append(mock.calls.DeleteOlderThan, callInfo)
	mock.lockDeleteOlderThan.Unlock()
	return mock.DeleteOlderThanFunc(ctx, age)
}

// DeleteOlderThanCalls gets all the calls that were made to DeleteOlderThan.
// Check the length with:
//
//	len(mockedIdempotencyUsecase.DeleteOlderThanCalls())
func (mock *IdempotencyUsecaseMock) DeleteOlderThanCalls() []struct {
	Ctx context.Context
	Age time.Duration
} {
	var calls []struct {
		Ctx context.Context
		Age time.Duration
	}
	mock.lockDeleteOlderThan.RLock()
	calls = mock.calls.DeleteOlderThan
	mock.lockDeleteOlderThan.RUnlock()
	return calls
}

// InsertIfNotExists calls InsertIfNotExistsFunc.
func (mock *IdempotencyUsecaseMock) InsertIfNotExists(ctx context.Context, key string, topic string, partition int32, offset int64) (bool, error) {
	if mock.InsertIfNotExistsFunc == nil {
		panic("IdempotencyUsecaseMock.InsertIfNotExistsFunc: method is nil but IdempotencyUsecase.InsertIfNotExists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Key       string
		Topic     string
		Partition int32
		Offset    int64
	}{
		Ctx:       ctx,
		Key:       key,
		Topic:     topic,
		Partition: partition,
		Offset:    offset,
	}
	mock.lockInsertIfNotExists.Lock()
	mock.calls.InsertIfNotExists = append(mock.calls.InsertIfNotExists, callInfo)
	mock.lockInsertIfNotExists.Unlock()
	return mock.InsertIfNotExistsFunc(ctx, key, topic, partition, offset)
}

// InsertIfNotExistsCalls gets all the calls that were made to InsertIfNotExists.
// Check the length with:
//
//	len(mockedIdempotencyUsecase.InsertIfNotExistsCalls())
func (mock *IdempotencyUsecaseMock) InsertIfNotExistsCalls() []struct {
	Ctx       context.Context
	Key       string
	Topic     string
	Partition int32
	Offset    int64
} {
	var calls []struct {
		Ctx       context.Context
		Key       string
		Topic     string
		Partition int32
		Offset    int64
	}
	mock.lockInsertIfNotExists.RLock()
	calls = mock.calls.InsertIfNotExists
	mock.lockInsertIfNotExists.RUnlock()
	return calls
}
