// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that ImageRepositoryMock does implement repository.ImageRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ImageRepository = &ImageRepositoryMock{}

// ImageRepositoryMock is a mock implementation of repository.ImageRepository.
//
//	func TestSomethingThatUsesImageRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ImageRepository
//		mockedImageRepository := &ImageRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, image *entity.Image) error {
//				panic("mock out the Create method")
//			},
//			FindByIDFunc: func(ctx context.Context, db *gorm.DB, image *entity.Image, id int64) error {
//				panic("mock out the FindByID method")
//			},
//			IncrementCommentCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementCommentCountByID method")
//			},
//			IncrementLikeCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementLikeCountByID method")
//			},
//		}
//
//		// use mockedImageRepository in code that requires repository.ImageRepository
//		// and then make assertions.
//
//	}
type ImageRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, image *entity.Image) error

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, db *gorm.DB, image *entity.Image, id int64) error

	// IncrementCommentCountByIDFunc mocks the IncrementCommentCountByID method.
	IncrementCommentCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// IncrementLikeCountByIDFunc mocks the IncrementLikeCountByID method.
	IncrementLikeCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Image is the image argument value.
			Image *entity.Image
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Image is the image argument value.
			Image *entity.Image
			// ID is the id argument value.
			ID int64
		}
		// IncrementCommentCountByID holds details about calls to the IncrementCommentCountByID method.
		IncrementCommentCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
		// IncrementLikeCountByID holds details about calls to the IncrementLikeCountByID method.
		IncrementLikeCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
	}
	lockCreate                    sync.RWMutex
	lockFindByID                  sync.RWMutex
	lockIncrementCommentCountByID sync.RWMutex
	lockIncrementLikeCountByID    sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ImageRepositoryMock) Create(ctx context.Context, db *gorm.DB, image *entity.Image) error {
	if mock.CreateFunc == nil {
		panic("ImageRepositoryMock.CreateFunc: method is nil but ImageRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
	}{
		Ctx:   ctx,
		Db:    db,
		Image: image,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, image)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedImageRepository.CreateCalls())
func (mock *ImageRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	Image *entity.Image
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *ImageRepositoryMock) FindByID(ctx context.Context, db *gorm.DB, image *entity.Image, id int64) error {
	if mock.FindByIDFunc == nil {
		panic("ImageRepositoryMock.FindByIDFunc: method is nil but ImageRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
		ID    int64
	}{
		Ctx:   ctx,
		Db:    db,
		Image: image,
		ID:    id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, db, image, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedImageRepository.FindByIDCalls())
func (mock *ImageRepositoryMock) FindByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	Image *entity.Image
	ID    int64
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		Image *entity.Image
		ID    int64
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// IncrementCommentCountByID calls IncrementCommentCountByIDFunc.
func (mock *ImageRepositoryMock) IncrementCommentCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementCommentCountByIDFunc == nil {
		panic("ImageRepositoryMock.IncrementCommentCountByIDFunc: method is nil but ImageRepository.IncrementCommentCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementCommentCountByID.Lock()
	mock.calls.IncrementCommentCountByID = append(mock.calls.IncrementCommentCountByID, callInfo)
	mock.lockIncrementCommentCountByID.Unlock()
	return mock.IncrementCommentCountByIDFunc(ctx, db, id, count)
}

// IncrementCommentCountByIDCalls gets all the calls that were made to IncrementCommentCountByID.
// Check the length with:
//
//	len(mockedImageRepository.IncrementCommentCountByIDCalls())
func (mock *ImageRepositoryMock) IncrementCommentCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementCommentCountByID.RLock()
	calls = mock.calls.IncrementCommentCountByID
	mock.lockIncrementCommentCountByID.RUnlock()
	return calls
}

// IncrementLikeCountByID calls IncrementLikeCountByIDFunc.
func (mock *ImageRepositoryMock) IncrementLikeCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementLikeCountByIDFunc == nil {
		panic("ImageRepositoryMock.IncrementLikeCountByIDFunc: method is nil but ImageRepository.IncrementLikeCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementLikeCountByID.Lock()
	mock.calls.IncrementLikeCountByID = append(mock.calls.IncrementLikeCountByID, callInfo)
	mock.lockIncrementLikeCountByID.Unlock()
	return mock.IncrementLikeCountByIDFunc(ctx, db, id, count)
}

// IncrementLikeCountByIDCalls gets all the calls that were made to IncrementLikeCountByID.
// Check the length with:
//
//	len(mockedImageRepository.IncrementLikeCountByIDCalls())
func (mock *ImageRepositoryMock) IncrementLikeCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementLikeCountByID.RLock()
	calls = mock.calls.IncrementLikeCountByID
	mock.lockIncrementLikeCountByID.RUnlock()
	return calls
}
