// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/outbound/repository"
	"gorm.io/gorm"
	"sync"
	"time"
)

// Ensure, that IdempotencyRepositoryMock does implement repository.IdempotencyRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.IdempotencyRepository = &IdempotencyRepositoryMock{}

// IdempotencyRepositoryMock is a mock implementation of repository.IdempotencyRepository.
//
//	func TestSomethingThatUsesIdempotencyRepository(t *testing.T) {
//
//		// make and configure a mocked repository.IdempotencyRepository
//		mockedIdempotencyRepository := &IdempotencyRepositoryMock{
//			DeleteOlderThanFunc: func(ctx context.Context, db *gorm.DB, age time.Duration) (int64, error) {
//				panic("mock out the DeleteOlderThan method")
//			},
//			InsertIfNotExistsFunc: func(ctx context.Context, db *gorm.DB, key string, topic string, partition int32, offset int64) (bool, error) {
//				panic("mock out the InsertIfNotExists method")
//			},
//		}
//
//		// use mockedIdempotencyRepository in code that requires repository.IdempotencyRepository
//		// and then make assertions.
//
//	}
type IdempotencyRepositoryMock struct {
	// DeleteOlderThanFunc mocks the DeleteOlderThan method.
	DeleteOlderThanFunc func(ctx context.Context, db *gorm.DB, age time.Duration) (int64, error)

	// InsertIfNotExistsFunc mocks the InsertIfNotExists method.
	InsertIfNotExistsFunc func(ctx context.Context, db *gorm.DB, key string, topic string, partition int32, offset int64) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteOlderThan holds details about calls to the DeleteOlderThan method.
		DeleteOlderThan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Age is the age argument value.
			Age time.Duration
		}
		// InsertIfNotExists holds details about calls to the InsertIfNotExists method.
		InsertIfNotExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Key is the key argument value.
			Key string
			// Topic is the topic argument value.
			Topic string
			// Partition is the partition argument value.
			Partition int32
			// Offset is the offset argument value.
			Offset int64
		}
	}
	lockDeleteOlderThan   sync.RWMutex
	lockInsertIfNotExists sync.RWMutex
}

// DeleteOlderThan calls DeleteOlderThanFunc.
func (mock *IdempotencyRepositoryMock) DeleteOlderThan(ctx context.Context, db *gorm.DB, age time.Duration) (int64, error) {
	if mock.DeleteOlderThanFunc == nil {
		panic("IdempotencyRepositoryMock.DeleteOlderThanFunc: method is nil but IdempotencyRepository.DeleteOlderThan was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Db  *gorm.DB
		Age time.Duration
	}{
		Ctx: ctx,
		Db:  db,
		Age: age,
	}
	mock.lockDeleteOlderThan.Lock()
	mock.calls.DeleteOlderThan = append(mock.calls.DeleteOlderThan, callInfo)
	mock.lockDeleteOlderThan.Unlock()
	return mock.DeleteOlderThanFunc(ctx, db, age)
}

// DeleteOlderThanCalls gets all the calls that were made to DeleteOlderThan.
// Check the length with:
//
//	len(mockedIdempotencyRepository.DeleteOlderThanCalls())
func (mock *IdempotencyRepositoryMock) DeleteOlderThanCalls() []struct {
	Ctx context.Context
	Db  *gorm.DB
	Age time.Duration
} {
	var calls []struct {
		Ctx context.Context
		Db  *gorm.DB
		Age time.Duration
	}
	mock.lockDeleteOlderThan.RLock()
	calls = mock.calls.DeleteOlderThan
	mock.lockDeleteOlderThan.RUnlock()
	return calls
}

// InsertIfNotExists calls InsertIfNotExistsFunc.
func (mock *IdempotencyRepositoryMock) InsertIfNotExists(ctx context.Context, db *gorm.DB, key string, topic string, partition int32, offset int64) (bool, error) {
	if mock.InsertIfNotExistsFunc == nil {
		panic("IdempotencyRepositoryMock.InsertIfNotExistsFunc: method is nil but IdempotencyRepository.InsertIfNotExists was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Db        *gorm.DB
		Key       string
		Topic     string
		Partition int32
		Offset    int64
	}{
		Ctx:       ctx,
		Db:        db,
		Key:       key,
		Topic:     topic,
		Partition: partition,
		Offset:    offset,
	}
	mock.lockInsertIfNotExists.Lock()
	mock.calls.InsertIfNotExists = append(mock.calls.InsertIfNotExists, callInfo)
	mock.lockInsertIfNotExists.Unlock()
	return mock.InsertIfNotExistsFunc(ctx, db, key, topic, partition, offset)
}

// InsertIfNotExistsCalls gets all the calls that were made to InsertIfNotExists.
// Check the length with:
//
//	len(mockedIdempotencyRepository.InsertIfNotExistsCalls())
func (mock *IdempotencyRepositoryMock) InsertIfNotExistsCalls() []struct {
	Ctx       context.Context
	Db        *gorm.DB
	Key       string
	Topic     string
	Partition int32
	Offset    int64
} {
	var calls []struct {
		Ctx       context.Context
		Db        *gorm.DB
		Key       string
		Topic     string
		Partition int32
		Offset    int64
	}
	mock.lockInsertIfNotExists.RLock()
	calls = mock.calls.InsertIfNotExists
	mock.lockInsertIfNotExists.RUnlock()
	return calls
}
