// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/infra/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that UserStatRepositoryMock does implement repository.UserStatRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.UserStatRepository = &UserStatRepositoryMock{}

// UserStatRepositoryMock is a mock implementation of repository.UserStatRepository.
//
//	func TestSomethingThatUsesUserStatRepository(t *testing.T) {
//
//		// make and configure a mocked repository.UserStatRepository
//		mockedUserStatRepository := &UserStatRepositoryMock{
//			IncrementFollowerCountAndFollowingCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error {
//				panic("mock out the IncrementFollowerCountAndFollowingCountByID method")
//			},
//			IncrementFollowerCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementFollowerCountByID method")
//			},
//			IncrementFollowingCountByIDFunc: func(ctx context.Context, db *gorm.DB, id int64, count int) error {
//				panic("mock out the IncrementFollowingCountByID method")
//			},
//		}
//
//		// use mockedUserStatRepository in code that requires repository.UserStatRepository
//		// and then make assertions.
//
//	}
type UserStatRepositoryMock struct {
	// IncrementFollowerCountAndFollowingCountByIDFunc mocks the IncrementFollowerCountAndFollowingCountByID method.
	IncrementFollowerCountAndFollowingCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error

	// IncrementFollowerCountByIDFunc mocks the IncrementFollowerCountByID method.
	IncrementFollowerCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// IncrementFollowingCountByIDFunc mocks the IncrementFollowingCountByID method.
	IncrementFollowingCountByIDFunc func(ctx context.Context, db *gorm.DB, id int64, count int) error

	// calls tracks calls to the methods.
	calls struct {
		// IncrementFollowerCountAndFollowingCountByID holds details about calls to the IncrementFollowerCountAndFollowingCountByID method.
		IncrementFollowerCountAndFollowingCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// FollowerCount is the followerCount argument value.
			FollowerCount int
			// FollowingCount is the followingCount argument value.
			FollowingCount int
		}
		// IncrementFollowerCountByID holds details about calls to the IncrementFollowerCountByID method.
		IncrementFollowerCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
		// IncrementFollowingCountByID holds details about calls to the IncrementFollowingCountByID method.
		IncrementFollowingCountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// ID is the id argument value.
			ID int64
			// Count is the count argument value.
			Count int
		}
	}
	lockIncrementFollowerCountAndFollowingCountByID sync.RWMutex
	lockIncrementFollowerCountByID                  sync.RWMutex
	lockIncrementFollowingCountByID                 sync.RWMutex
}

// IncrementFollowerCountAndFollowingCountByID calls IncrementFollowerCountAndFollowingCountByIDFunc.
func (mock *UserStatRepositoryMock) IncrementFollowerCountAndFollowingCountByID(ctx context.Context, db *gorm.DB, id int64, followerCount int, followingCount int) error {
	if mock.IncrementFollowerCountAndFollowingCountByIDFunc == nil {
		panic("UserStatRepositoryMock.IncrementFollowerCountAndFollowingCountByIDFunc: method is nil but UserStatRepository.IncrementFollowerCountAndFollowingCountByID was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		ID             int64
		FollowerCount  int
		FollowingCount int
	}{
		Ctx:            ctx,
		Db:             db,
		ID:             id,
		FollowerCount:  followerCount,
		FollowingCount: followingCount,
	}
	mock.lockIncrementFollowerCountAndFollowingCountByID.Lock()
	mock.calls.IncrementFollowerCountAndFollowingCountByID = append(mock.calls.IncrementFollowerCountAndFollowingCountByID, callInfo)
	mock.lockIncrementFollowerCountAndFollowingCountByID.Unlock()
	return mock.IncrementFollowerCountAndFollowingCountByIDFunc(ctx, db, id, followerCount, followingCount)
}

// IncrementFollowerCountAndFollowingCountByIDCalls gets all the calls that were made to IncrementFollowerCountAndFollowingCountByID.
// Check the length with:
//
//	len(mockedUserStatRepository.IncrementFollowerCountAndFollowingCountByIDCalls())
func (mock *UserStatRepositoryMock) IncrementFollowerCountAndFollowingCountByIDCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	ID             int64
	FollowerCount  int
	FollowingCount int
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		ID             int64
		FollowerCount  int
		FollowingCount int
	}
	mock.lockIncrementFollowerCountAndFollowingCountByID.RLock()
	calls = mock.calls.IncrementFollowerCountAndFollowingCountByID
	mock.lockIncrementFollowerCountAndFollowingCountByID.RUnlock()
	return calls
}

// IncrementFollowerCountByID calls IncrementFollowerCountByIDFunc.
func (mock *UserStatRepositoryMock) IncrementFollowerCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementFollowerCountByIDFunc == nil {
		panic("UserStatRepositoryMock.IncrementFollowerCountByIDFunc: method is nil but UserStatRepository.IncrementFollowerCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementFollowerCountByID.Lock()
	mock.calls.IncrementFollowerCountByID = append(mock.calls.IncrementFollowerCountByID, callInfo)
	mock.lockIncrementFollowerCountByID.Unlock()
	return mock.IncrementFollowerCountByIDFunc(ctx, db, id, count)
}

// IncrementFollowerCountByIDCalls gets all the calls that were made to IncrementFollowerCountByID.
// Check the length with:
//
//	len(mockedUserStatRepository.IncrementFollowerCountByIDCalls())
func (mock *UserStatRepositoryMock) IncrementFollowerCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementFollowerCountByID.RLock()
	calls = mock.calls.IncrementFollowerCountByID
	mock.lockIncrementFollowerCountByID.RUnlock()
	return calls
}

// IncrementFollowingCountByID calls IncrementFollowingCountByIDFunc.
func (mock *UserStatRepositoryMock) IncrementFollowingCountByID(ctx context.Context, db *gorm.DB, id int64, count int) error {
	if mock.IncrementFollowingCountByIDFunc == nil {
		panic("UserStatRepositoryMock.IncrementFollowingCountByIDFunc: method is nil but UserStatRepository.IncrementFollowingCountByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}{
		Ctx:   ctx,
		Db:    db,
		ID:    id,
		Count: count,
	}
	mock.lockIncrementFollowingCountByID.Lock()
	mock.calls.IncrementFollowingCountByID = append(mock.calls.IncrementFollowingCountByID, callInfo)
	mock.lockIncrementFollowingCountByID.Unlock()
	return mock.IncrementFollowingCountByIDFunc(ctx, db, id, count)
}

// IncrementFollowingCountByIDCalls gets all the calls that were made to IncrementFollowingCountByID.
// Check the length with:
//
//	len(mockedUserStatRepository.IncrementFollowingCountByIDCalls())
func (mock *UserStatRepositoryMock) IncrementFollowingCountByIDCalls() []struct {
	Ctx   context.Context
	Db    *gorm.DB
	ID    int64
	Count int
} {
	var calls []struct {
		Ctx   context.Context
		Db    *gorm.DB
		ID    int64
		Count int
	}
	mock.lockIncrementFollowingCountByID.RLock()
	calls = mock.calls.IncrementFollowingCountByID
	mock.lockIncrementFollowingCountByID.RUnlock()
	return calls
}
