// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/outbound/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that OutboxRepositoryMock does implement repository.OutboxRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.OutboxRepository = &OutboxRepositoryMock{}

// OutboxRepositoryMock is a mock implementation of repository.OutboxRepository.
//
//	func TestSomethingThatUsesOutboxRepository(t *testing.T) {
//
//		// make and configure a mocked repository.OutboxRepository
//		mockedOutboxRepository := &OutboxRepositoryMock{
//			FindPendingFunc: func(ctx context.Context, db *gorm.DB, outboxes *entity.OutboxList, limit int) error {
//				panic("mock out the FindPending method")
//			},
//			InsertFunc: func(ctx context.Context, db *gorm.DB, outbox *entity.Outbox) error {
//				panic("mock out the Insert method")
//			},
//			MarkProducedFunc: func(ctx context.Context, db *gorm.DB, ids []int64) error {
//				panic("mock out the MarkProduced method")
//			},
//		}
//
//		// use mockedOutboxRepository in code that requires repository.OutboxRepository
//		// and then make assertions.
//
//	}
type OutboxRepositoryMock struct {
	// FindPendingFunc mocks the FindPending method.
	FindPendingFunc func(ctx context.Context, db *gorm.DB, outboxes *entity.OutboxList, limit int) error

	// InsertFunc mocks the Insert method.
	InsertFunc func(ctx context.Context, db *gorm.DB, outbox *entity.Outbox) error

	// MarkProducedFunc mocks the MarkProduced method.
	MarkProducedFunc func(ctx context.Context, db *gorm.DB, ids []int64) error

	// calls tracks calls to the methods.
	calls struct {
		// FindPending holds details about calls to the FindPending method.
		FindPending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Outboxes is the outboxes argument value.
			Outboxes *entity.OutboxList
			// Limit is the limit argument value.
			Limit int
		}
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Outbox is the outbox argument value.
			Outbox *entity.Outbox
		}
		// MarkProduced holds details about calls to the MarkProduced method.
		MarkProduced []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Ids is the ids argument value.
			Ids []int64
		}
	}
	lockFindPending  sync.RWMutex
	lockInsert       sync.RWMutex
	lockMarkProduced sync.RWMutex
}

// FindPending calls FindPendingFunc.
func (mock *OutboxRepositoryMock) FindPending(ctx context.Context, db *gorm.DB, outboxes *entity.OutboxList, limit int) error {
	if mock.FindPendingFunc == nil {
		panic("OutboxRepositoryMock.FindPendingFunc: method is nil but OutboxRepository.FindPending was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Db       *gorm.DB
		Outboxes *entity.OutboxList
		Limit    int
	}{
		Ctx:      ctx,
		Db:       db,
		Outboxes: outboxes,
		Limit:    limit,
	}
	mock.lockFindPending.Lock()
	mock.calls.FindPending = append(mock.calls.FindPending, callInfo)
	mock.lockFindPending.Unlock()
	return mock.FindPendingFunc(ctx, db, outboxes, limit)
}

// FindPendingCalls gets all the calls that were made to FindPending.
// Check the length with:
//
//	len(mockedOutboxRepository.FindPendingCalls())
func (mock *OutboxRepositoryMock) FindPendingCalls() []struct {
	Ctx      context.Context
	Db       *gorm.DB
	Outboxes *entity.OutboxList
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		Db       *gorm.DB
		Outboxes *entity.OutboxList
		Limit    int
	}
	mock.lockFindPending.RLock()
	calls = mock.calls.FindPending
	mock.lockFindPending.RUnlock()
	return calls
}

// Insert calls InsertFunc.
func (mock *OutboxRepositoryMock) Insert(ctx context.Context, db *gorm.DB, outbox *entity.Outbox) error {
	if mock.InsertFunc == nil {
		panic("OutboxRepositoryMock.InsertFunc: method is nil but OutboxRepository.Insert was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Db     *gorm.DB
		Outbox *entity.Outbox
	}{
		Ctx:    ctx,
		Db:     db,
		Outbox: outbox,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(ctx, db, outbox)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedOutboxRepository.InsertCalls())
func (mock *OutboxRepositoryMock) InsertCalls() []struct {
	Ctx    context.Context
	Db     *gorm.DB
	Outbox *entity.Outbox
} {
	var calls []struct {
		Ctx    context.Context
		Db     *gorm.DB
		Outbox *entity.Outbox
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}

// MarkProduced calls MarkProducedFunc.
func (mock *OutboxRepositoryMock) MarkProduced(ctx context.Context, db *gorm.DB, ids []int64) error {
	if mock.MarkProducedFunc == nil {
		panic("OutboxRepositoryMock.MarkProducedFunc: method is nil but OutboxRepository.MarkProduced was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Db  *gorm.DB
		Ids []int64
	}{
		Ctx: ctx,
		Db:  db,
		Ids: ids,
	}
	mock.lockMarkProduced.Lock()
	mock.calls.MarkProduced = append(mock.calls.MarkProduced, callInfo)
	mock.lockMarkProduced.Unlock()
	return mock.MarkProducedFunc(ctx, db, ids)
}

// MarkProducedCalls gets all the calls that were made to MarkProduced.
// Check the length with:
//
//	len(mockedOutboxRepository.MarkProducedCalls())
func (mock *OutboxRepositoryMock) MarkProducedCalls() []struct {
	Ctx context.Context
	Db  *gorm.DB
	Ids []int64
} {
	var calls []struct {
		Ctx context.Context
		Db  *gorm.DB
		Ids []int64
	}
	mock.lockMarkProduced.RLock()
	calls = mock.calls.MarkProduced
	mock.lockMarkProduced.RUnlock()
	return calls
}
