// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/outbound/messaging"
	"sync"
)

// Ensure, that OutboxProducerMock does implement messaging.OutboxProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.OutboxProducer = &OutboxProducerMock{}

// OutboxProducerMock is a mock implementation of messaging.OutboxProducer.
//
//	func TestSomethingThatUsesOutboxProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.OutboxProducer
//		mockedOutboxProducer := &OutboxProducerMock{
//			ProducePendingFunc: func(ctx context.Context) error {
//				panic("mock out the ProducePending method")
//			},
//		}
//
//		// use mockedOutboxProducer in code that requires messaging.OutboxProducer
//		// and then make assertions.
//
//	}
type OutboxProducerMock struct {
	// ProducePendingFunc mocks the ProducePending method.
	ProducePendingFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// ProducePending holds details about calls to the ProducePending method.
		ProducePending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockProducePending sync.RWMutex
}

// ProducePending calls ProducePendingFunc.
func (mock *OutboxProducerMock) ProducePending(ctx context.Context) error {
	if mock.ProducePendingFunc == nil {
		panic("OutboxProducerMock.ProducePendingFunc: method is nil but OutboxProducer.ProducePending was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockProducePending.Lock()
	mock.calls.ProducePending = append(mock.calls.ProducePending, callInfo)
	mock.lockProducePending.Unlock()
	return mock.ProducePendingFunc(ctx)
}

// ProducePendingCalls gets all the calls that were made to ProducePending.
// Check the length with:
//
//	len(mockedOutboxProducer.ProducePendingCalls())
func (mock *OutboxProducerMock) ProducePendingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockProducePending.RLock()
	calls = mock.calls.ProducePending
	mock.lockProducePending.RUnlock()
	return calls
}
