// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/outbound/messaging"
	"sync"
)

// Ensure, that OutboxPublisherMock does implement messaging.OutboxPublisher.
// If this is not the case, regenerate this file with moq.
var _ messaging.OutboxPublisher = &OutboxPublisherMock{}

// OutboxPublisherMock is a mock implementation of messaging.OutboxPublisher.
//
//	func TestSomethingThatUsesOutboxPublisher(t *testing.T) {
//
//		// make and configure a mocked messaging.OutboxPublisher
//		mockedOutboxPublisher := &OutboxPublisherMock{
//			PublishPendingFunc: func(ctx context.Context) error {
//				panic("mock out the PublishPending method")
//			},
//		}
//
//		// use mockedOutboxPublisher in code that requires messaging.OutboxPublisher
//		// and then make assertions.
//
//	}
type OutboxPublisherMock struct {
	// PublishPendingFunc mocks the PublishPending method.
	PublishPendingFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// PublishPending holds details about calls to the PublishPending method.
		PublishPending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPublishPending sync.RWMutex
}

// PublishPending calls PublishPendingFunc.
func (mock *OutboxPublisherMock) PublishPending(ctx context.Context) error {
	if mock.PublishPendingFunc == nil {
		panic("OutboxPublisherMock.PublishPendingFunc: method is nil but OutboxPublisher.PublishPending was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPublishPending.Lock()
	mock.calls.PublishPending = append(mock.calls.PublishPending, callInfo)
	mock.lockPublishPending.Unlock()
	return mock.PublishPendingFunc(ctx)
}

// PublishPendingCalls gets all the calls that were made to PublishPending.
// Check the length with:
//
//	len(mockedOutboxPublisher.PublishPendingCalls())
func (mock *OutboxPublisherMock) PublishPendingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPublishPending.RLock()
	calls = mock.calls.PublishPending
	mock.lockPublishPending.RUnlock()
	return calls
}
