// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/messaging"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that ImageProducerMock does implement messaging.ImageProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.ImageProducer = &ImageProducerMock{}

// ImageProducerMock is a mock implementation of messaging.ImageProducer.
//
//	func TestSomethingThatUsesImageProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.ImageProducer
//		mockedImageProducer := &ImageProducerMock{
//			SendImageCommentedFunc: func(ctx context.Context, event *model.ImageCommentedEvent) error {
//				panic("mock out the SendImageCommented method")
//			},
//			SendImageLikedFunc: func(ctx context.Context, event *model.ImageLikedEvent) error {
//				panic("mock out the SendImageLiked method")
//			},
//			SendImageUploadedFunc: func(ctx context.Context, event *model.ImageUploadedEvent) error {
//				panic("mock out the SendImageUploaded method")
//			},
//		}
//
//		// use mockedImageProducer in code that requires messaging.ImageProducer
//		// and then make assertions.
//
//	}
type ImageProducerMock struct {
	// SendImageCommentedFunc mocks the SendImageCommented method.
	SendImageCommentedFunc func(ctx context.Context, event *model.ImageCommentedEvent) error

	// SendImageLikedFunc mocks the SendImageLiked method.
	SendImageLikedFunc func(ctx context.Context, event *model.ImageLikedEvent) error

	// SendImageUploadedFunc mocks the SendImageUploaded method.
	SendImageUploadedFunc func(ctx context.Context, event *model.ImageUploadedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// SendImageCommented holds details about calls to the SendImageCommented method.
		SendImageCommented []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageCommentedEvent
		}
		// SendImageLiked holds details about calls to the SendImageLiked method.
		SendImageLiked []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageLikedEvent
		}
		// SendImageUploaded holds details about calls to the SendImageUploaded method.
		SendImageUploaded []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ImageUploadedEvent
		}
	}
	lockSendImageCommented sync.RWMutex
	lockSendImageLiked     sync.RWMutex
	lockSendImageUploaded  sync.RWMutex
}

// SendImageCommented calls SendImageCommentedFunc.
func (mock *ImageProducerMock) SendImageCommented(ctx context.Context, event *model.ImageCommentedEvent) error {
	if mock.SendImageCommentedFunc == nil {
		panic("ImageProducerMock.SendImageCommentedFunc: method is nil but ImageProducer.SendImageCommented was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageCommentedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSendImageCommented.Lock()
	mock.calls.SendImageCommented = append(mock.calls.SendImageCommented, callInfo)
	mock.lockSendImageCommented.Unlock()
	return mock.SendImageCommentedFunc(ctx, event)
}

// SendImageCommentedCalls gets all the calls that were made to SendImageCommented.
// Check the length with:
//
//	len(mockedImageProducer.SendImageCommentedCalls())
func (mock *ImageProducerMock) SendImageCommentedCalls() []struct {
	Ctx   context.Context
	Event *model.ImageCommentedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageCommentedEvent
	}
	mock.lockSendImageCommented.RLock()
	calls = mock.calls.SendImageCommented
	mock.lockSendImageCommented.RUnlock()
	return calls
}

// SendImageLiked calls SendImageLikedFunc.
func (mock *ImageProducerMock) SendImageLiked(ctx context.Context, event *model.ImageLikedEvent) error {
	if mock.SendImageLikedFunc == nil {
		panic("ImageProducerMock.SendImageLikedFunc: method is nil but ImageProducer.SendImageLiked was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageLikedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSendImageLiked.Lock()
	mock.calls.SendImageLiked = append(mock.calls.SendImageLiked, callInfo)
	mock.lockSendImageLiked.Unlock()
	return mock.SendImageLikedFunc(ctx, event)
}

// SendImageLikedCalls gets all the calls that were made to SendImageLiked.
// Check the length with:
//
//	len(mockedImageProducer.SendImageLikedCalls())
func (mock *ImageProducerMock) SendImageLikedCalls() []struct {
	Ctx   context.Context
	Event *model.ImageLikedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageLikedEvent
	}
	mock.lockSendImageLiked.RLock()
	calls = mock.calls.SendImageLiked
	mock.lockSendImageLiked.RUnlock()
	return calls
}

// SendImageUploaded calls SendImageUploadedFunc.
func (mock *ImageProducerMock) SendImageUploaded(ctx context.Context, event *model.ImageUploadedEvent) error {
	if mock.SendImageUploadedFunc == nil {
		panic("ImageProducerMock.SendImageUploadedFunc: method is nil but ImageProducer.SendImageUploaded was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ImageUploadedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSendImageUploaded.Lock()
	mock.calls.SendImageUploaded = append(mock.calls.SendImageUploaded, callInfo)
	mock.lockSendImageUploaded.Unlock()
	return mock.SendImageUploadedFunc(ctx, event)
}

// SendImageUploadedCalls gets all the calls that were made to SendImageUploaded.
// Check the length with:
//
//	len(mockedImageProducer.SendImageUploadedCalls())
func (mock *ImageProducerMock) SendImageUploadedCalls() []struct {
	Ctx   context.Context
	Event *model.ImageUploadedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ImageUploadedEvent
	}
	mock.lockSendImageUploaded.RLock()
	calls = mock.calls.SendImageUploaded
	mock.lockSendImageUploaded.RUnlock()
	return calls
}
