// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/entity"
	"github.com/Hidayathamir/golang-clean-architecture/internal/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that UserRepositoryMock does implement repository.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of repository.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked repository.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountByUsernameFunc: func(ctx context.Context, db *gorm.DB, username string) (int64, error) {
//				panic("mock out the CountByUsername method")
//			},
//			CreateFunc: func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error {
//				panic("mock out the Create method")
//			},
//			FindByIDFunc: func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, id int64) error {
//				panic("mock out the FindByID method")
//			},
//			FindByUsernameFunc: func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, username string) error {
//				panic("mock out the FindByUsername method")
//			},
//			UpdateFunc: func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires repository.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountByUsernameFunc mocks the CountByUsername method.
	CountByUsernameFunc func(ctx context.Context, db *gorm.DB, username string) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, id int64) error

	// FindByUsernameFunc mocks the FindByUsername method.
	FindByUsernameFunc func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, username string) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error

	// calls tracks calls to the methods.
	calls struct {
		// CountByUsername holds details about calls to the CountByUsername method.
		CountByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Username is the username argument value.
			Username string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.User
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.User
			// ID is the id argument value.
			ID int64
		}
		// FindByUsername holds details about calls to the FindByUsername method.
		FindByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.User
			// Username is the username argument value.
			Username string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// EntityMoqParam is the entityMoqParam argument value.
			EntityMoqParam *entity.User
		}
	}
	lockCountByUsername sync.RWMutex
	lockCreate          sync.RWMutex
	lockFindByID        sync.RWMutex
	lockFindByUsername  sync.RWMutex
	lockUpdate          sync.RWMutex
}

// CountByUsername calls CountByUsernameFunc.
func (mock *UserRepositoryMock) CountByUsername(ctx context.Context, db *gorm.DB, username string) (int64, error) {
	if mock.CountByUsernameFunc == nil {
		panic("UserRepositoryMock.CountByUsernameFunc: method is nil but UserRepository.CountByUsername was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Db       *gorm.DB
		Username string
	}{
		Ctx:      ctx,
		Db:       db,
		Username: username,
	}
	mock.lockCountByUsername.Lock()
	mock.calls.CountByUsername = append(mock.calls.CountByUsername, callInfo)
	mock.lockCountByUsername.Unlock()
	return mock.CountByUsernameFunc(ctx, db, username)
}

// CountByUsernameCalls gets all the calls that were made to CountByUsername.
// Check the length with:
//
//	len(mockedUserRepository.CountByUsernameCalls())
func (mock *UserRepositoryMock) CountByUsernameCalls() []struct {
	Ctx      context.Context
	Db       *gorm.DB
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Db       *gorm.DB
		Username string
	}
	mock.lockCountByUsername.RLock()
	calls = mock.calls.CountByUsername
	mock.lockCountByUsername.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
	}{
		Ctx:            ctx,
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, entityMoqParam)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	EntityMoqParam *entity.User
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, id int64) error {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
		ID             int64
	}{
		Ctx:            ctx,
		Db:             db,
		EntityMoqParam: entityMoqParam,
		ID:             id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, db, entityMoqParam, id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	EntityMoqParam *entity.User
	ID             int64
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
		ID             int64
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByUsername calls FindByUsernameFunc.
func (mock *UserRepositoryMock) FindByUsername(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User, username string) error {
	if mock.FindByUsernameFunc == nil {
		panic("UserRepositoryMock.FindByUsernameFunc: method is nil but UserRepository.FindByUsername was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
		Username       string
	}{
		Ctx:            ctx,
		Db:             db,
		EntityMoqParam: entityMoqParam,
		Username:       username,
	}
	mock.lockFindByUsername.Lock()
	mock.calls.FindByUsername = append(mock.calls.FindByUsername, callInfo)
	mock.lockFindByUsername.Unlock()
	return mock.FindByUsernameFunc(ctx, db, entityMoqParam, username)
}

// FindByUsernameCalls gets all the calls that were made to FindByUsername.
// Check the length with:
//
//	len(mockedUserRepository.FindByUsernameCalls())
func (mock *UserRepositoryMock) FindByUsernameCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	EntityMoqParam *entity.User
	Username       string
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
		Username       string
	}
	mock.lockFindByUsername.RLock()
	calls = mock.calls.FindByUsername
	mock.lockFindByUsername.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(ctx context.Context, db *gorm.DB, entityMoqParam *entity.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
	}{
		Ctx:            ctx,
		Db:             db,
		EntityMoqParam: entityMoqParam,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, db, entityMoqParam)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	Ctx            context.Context
	Db             *gorm.DB
	EntityMoqParam *entity.User
} {
	var calls []struct {
		Ctx            context.Context
		Db             *gorm.DB
		EntityMoqParam *entity.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
