// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"golang-clean-architecture/internal/gateway/messaging"
	"golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that UserProducerMock does implement messaging.UserProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.UserProducer = &UserProducerMock{}

// UserProducerMock is a mock implementation of messaging.UserProducer.
//
//	func TestSomethingThatUsesUserProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.UserProducer
//		mockedUserProducer := &UserProducerMock{
//			SendFunc: func(event *model.UserEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedUserProducer in code that requires messaging.UserProducer
//		// and then make assertions.
//
//	}
type UserProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(event *model.UserEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Event is the event argument value.
			Event *model.UserEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *UserProducerMock) Send(event *model.UserEvent) error {
	if mock.SendFunc == nil {
		panic("UserProducerMock.SendFunc: method is nil but UserProducer.Send was just called")
	}
	callInfo := struct {
		Event *model.UserEvent
	}{
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedUserProducer.SendCalls())
func (mock *UserProducerMock) SendCalls() []struct {
	Event *model.UserEvent
} {
	var calls []struct {
		Event *model.UserEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
