// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/golang-clean-architecture/internal/gateway/messaging"
	"github.com/Hidayathamir/golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that UserFollowedProducerMock does implement messaging.UserFollowedProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.UserFollowedProducer = &UserFollowedProducerMock{}

// UserFollowedProducerMock is a mock implementation of messaging.UserFollowedProducer.
//
//	func TestSomethingThatUsesUserFollowedProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.UserFollowedProducer
//		mockedUserFollowedProducer := &UserFollowedProducerMock{
//			SendFunc: func(ctx context.Context, event *model.UserFollowedEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedUserFollowedProducer in code that requires messaging.UserFollowedProducer
//		// and then make assertions.
//
//	}
type UserFollowedProducerMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, event *model.UserFollowedEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.UserFollowedEvent
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *UserFollowedProducerMock) Send(ctx context.Context, event *model.UserFollowedEvent) error {
	if mock.SendFunc == nil {
		panic("UserFollowedProducerMock.SendFunc: method is nil but UserFollowedProducer.Send was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.UserFollowedEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedUserFollowedProducer.SendCalls())
func (mock *UserFollowedProducerMock) SendCalls() []struct {
	Ctx   context.Context
	Event *model.UserFollowedEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.UserFollowedEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
