// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"golang-clean-architecture/internal/gateway/messaging"
	"golang-clean-architecture/internal/model"
	"sync"
)

// Ensure, that UserProducerMock does implement messaging.UserProducer.
// If this is not the case, regenerate this file with moq.
var _ messaging.UserProducer = &UserProducerMock{}

// UserProducerMock is a mock implementation of messaging.UserProducer.
//
//	func TestSomethingThatUsesUserProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.UserProducer
//		mockedUserProducer := &UserProducerMock{
//			GetTopicFunc: func() *string {
//				panic("mock out the GetTopic method")
//			},
//			SendFunc: func(event *model.UserEvent) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedUserProducer in code that requires messaging.UserProducer
//		// and then make assertions.
//
//	}
type UserProducerMock struct {
	// GetTopicFunc mocks the GetTopic method.
	GetTopicFunc func() *string

	// SendFunc mocks the Send method.
	SendFunc func(event *model.UserEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// GetTopic holds details about calls to the GetTopic method.
		GetTopic []struct {
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Event is the event argument value.
			Event *model.UserEvent
		}
	}
	lockGetTopic sync.RWMutex
	lockSend     sync.RWMutex
}

// GetTopic calls GetTopicFunc.
func (mock *UserProducerMock) GetTopic() *string {
	if mock.GetTopicFunc == nil {
		panic("UserProducerMock.GetTopicFunc: method is nil but UserProducer.GetTopic was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTopic.Lock()
	mock.calls.GetTopic = append(mock.calls.GetTopic, callInfo)
	mock.lockGetTopic.Unlock()
	return mock.GetTopicFunc()
}

// GetTopicCalls gets all the calls that were made to GetTopic.
// Check the length with:
//
//	len(mockedUserProducer.GetTopicCalls())
func (mock *UserProducerMock) GetTopicCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTopic.RLock()
	calls = mock.calls.GetTopic
	mock.lockGetTopic.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *UserProducerMock) Send(event *model.UserEvent) error {
	if mock.SendFunc == nil {
		panic("UserProducerMock.SendFunc: method is nil but UserProducer.Send was just called")
	}
	callInfo := struct {
		Event *model.UserEvent
	}{
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedUserProducer.SendCalls())
func (mock *UserProducerMock) SendCalls() []struct {
	Event *model.UserEvent
} {
	var calls []struct {
		Event *model.UserEvent
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
